### ISSUE TITLE
iCloud image not supported

### ISSUE THREAD

**Issue by magrinj** [ivpusic/react-native-image-crop-picker#81] opened 2016-09-22 10:07 UTC
Hi everyone,

I just see that iCloud image are not supported by `QBImagePickerController`, I try to implement another library that work with icloud image, this one: `CTAssetsPickerController`, but this one can only select multiple image, we can't force the user to be able to only select one picture, so maybe we can just use `UIImagePikcerController` when the multiple choice is `off`, what do you think about it ?

I'm better in Swift than Objective-C, but I'm going to try to make a PR on the old library or implement the new one.

If someone got another idea, or know how to fix the problem in `QBImagePickerController` just post bellow :D 

Thanks!

**Comment by ivpusic** [comment] 2016-09-22 10:47
one thing I can see is that probably feature from this PR https://github.com/ivpusic/react-native-image-crop-picker/pull/68 won't work anymore?

**Comment by magrinj** [comment] 2016-09-22 11:34
Yes you're right, I find another library used by Facebook that maybe can implement this PR and work also with single choice:
http://cocoadocs.org/docsets/DKImagePickerController/3.3.4/
What do you think about this one ?

**Comment by ivpusic** [comment] 2016-09-22 11:56
doesn't look bad. This would be a huge change, and I don't have time to do it. 

So far QBImagePicker works very well on my projects. 
As far as I can see this library is not used by facebook, but it is "Facebook style" image picker, so this is another part where someone should spend some time to really verify that is works for all features we have so far.

**Comment by magrinj** [comment] 2016-09-22 11:58
Ok, I'm going to look into it, because I use your library in one of my project, and all user that have image save in iCloud in there library can't select and crop the picture :/

If I made it, I'll do a PR !

**Comment by ivpusic** [comment] 2016-09-22 12:03
great. then for now let's close this issue.

**Closed by ivpusic** 2016-09-22 12:03 UTC

**Comment by superandrew213** [comment] 2016-09-22 12:59
@magrinj I had the same issue, so for now I just disabled the iCloud library. A fix for this would be awesome, let us know how you go.

**Comment by magrinj** [comment] 2016-09-22 13:00
@superandrew213 How did you disable iCloud library ? That's will be a good quick fix for me, and allow me to link the other library by taking my time :)

**Comment by superandrew213** [comment] 2016-09-22 13:03
@magrinj I added the smartAlbums option a few days ago to react-native-image-crop-picker for this reason. The default value is ['UserLibrary', 'PhotoStream', 'Panoramas', 'Videos', 'Bursts']. Just remove 'PhotoStream' which stands for the iCloud library

**Comment by superandrew213** [comment] 2016-09-22 13:04
Should be in the readme

**Comment by magrinj** [comment] 2016-09-22 13:05
Ok perfect, thank you very much! 👍

**Comment by magrinj** [comment] 2016-09-22 13:44
Your solution is not working for me, if I remove 'PhotoStream', I still have photo that are store on iCloud in 'UserLibrary' :/

**Comment by superandrew213** [comment] 2016-09-22 14:08
@magrinj it should remove the icloud library form the list of available albums if you use this ```smartAlbums: ['UserLibrary', 'Panoramas', 'Videos', 'Bursts']```. 
Did you update to latest version of react-native-image-crop-picker?

**Comment by magrinj** [comment] 2016-09-22 14:11
@superandrew213 Yes I update to the last version of `react-native-image-crop-picker`, and I also apply the same smartAlbums as you, but the problem is that in the `UserLibrary` some pictures are stored on iCloud because I select the optimize storage for my iPhone, so the problem still the same even with `smartAlbums` :/

**Comment by superandrew213** [comment] 2016-09-22 14:14
Ah ok I got you. I never use iCloud so I didn't know you could have iCloud photos in the UserLibrary. That's a bummer. We need to come up with a proper fix for this then

**Comment by magrinj** [comment] 2016-09-22 14:16
Yes, I'm looking into it, and I try to find another library that work with iCloud picture and can have a sort of `smartAlbums`, I find this one working like `QBImagePicker` : https://github.com/guillermomuntaner/GMImagePicker/blob/master/GMImagePicker/GMImagePickerController.m

But I don't really know if this one work with iCloud picture :/

**Comment by ivpusic** [comment] 2016-09-22 15:21
@magrinj I also don't have iCloud photos so I cannot reproduce issue. Can you tell me what exactly happens when user select photo stored on iCloud? QBImagePicker crashes or `openPicker` promise just rejects with some error message?

**Comment by magrinj** [comment] 2016-09-22 15:25
@ivpusic When you select an icloud picture, `QBImagePicker` return a `nil` picture, so the cropper appear with no image, so you can't click on `Choose` but only on `Cancel`, and no image are returned

**Comment by ivpusic** [comment] 2016-09-22 16:07
hm, so for now we should add check if image is nil, and call cropping only if we got image data. Otherwise reject promise with proper error message.

**Comment by magrinj** [comment] 2016-09-22 16:11
Yes that's can be a temporary solution, I try to take a look into implementing the library `DKImagePickerController` but my level in Objective-C is not good enough to do it :/

**Comment by magrinj** [comment] 2016-09-27 15:48
#87

**Comment by srameshr** [comment] 2017-10-24 10:21
```
smartAlbums: [
          'UserLibrary',
          'PhotoStream',
          'Panoramas',
          'Bursts',
          'Places',
          'LivePhotos',
          'DepthEffect',
          'Screenshots',
          'RecentlyAdded',
          'Timelapses',
          'Favorites',
          'Genreic',
          'CloudShared',
          'Imported',
          'SyncedAlbum',
          'SyncedFaces',
          'Regular',
        ]
```
This is my smartAlbums option and none of them work except for the defaults ones mentioned in the docs. Most used albums like ```SelfPortraits``` and ```CloudShared``` wont even appear.

**Comment by superandrew213** [comment] 2017-10-24 11:29
Only these options are supported
https://github.com/ivpusic/react-native-image-crop-picker/blob/c44ce340e0ecc957d69d631e020d979e170be09d/ios/ImageCropPicker.m#L256-L262

**Comment by srameshr** [comment] 2017-10-24 11:46
@superandrew213  Cant we add more to this?

**Comment by superandrew213** [comment] 2017-10-24 12:18
This package uses https://github.com/questbeat/QBImagePicker. You have to request this feature there

**Comment by srameshr** [comment] 2017-10-24 12:33
That was updates 2 years ago. So, we would not see this here?

**Comment by magrinj** [comment] 2018-06-18 15:02
@srameshr I think you should create another ticket for your question instead of commenting this one.
As @superandrew213 this package use QBImagePicker, so try to make a PR for this one, or create a ticket to suggest a new library ;)

@cfontana0 If your question is for the iCloud support it's fixed, if it's the same question as @srameshr you should do the same.

**Comment by theohdv** [comment] 2018-06-18 15:58
My PR #655 should fix that
