### ISSUE TITLE
RSKImageCropper.framework contains unsupported architectures '[x86_64, i386]'

### ISSUE THREAD

**Issue by jo2010** [ivpusic/react-native-image-crop-picker#76] opened 2016-09-18 04:21 UTC
- react-native-image-crop-picker 0.9.3
- react-native v0.33

Getting the following when I try to upload the iOS app using Application Loader. No issues with Android.

```
Package(s) were not uploaded because they had problems:
	/var/folders/l0/mnr9xkh14bgfg2bxt_p36y6h0000gn/T/05ED8030-5775-425E-BA0E-A0D873EED816/1155871701.itmsp - Error Messages:
		ERROR ITMS-90087: "Unsupported Architectures. The executable for myApp.app/Frameworks/QBImagePicker.framework contains unsupported architectures '[x86_64, i386]'."
		ERROR ITMS-90087: "Unsupported Architectures. The executable for myApp.app/Frameworks/RSKImageCropper.framework contains unsupported architectures '[x86_64, i386]'."
		ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "myApp.app/Frameworks/QBImagePicker.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode and machine code) and arm64(bitcode and machine code), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
		ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "myApp.app/Frameworks/RSKImageCropper.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode and machine code) and arm64(bitcode and machine code), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'myApp.app/Frameworks/QBImagePicker.framework/QBImagePicker' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'myApp.app/Frameworks/RSKImageCropper.framework/RSKImageCropper' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

```

**Comment by ivpusic** [comment] 2016-09-18 10:46
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/61

**Closed by ivpusic** 2016-09-18 10:46 UTC

**Comment by jo2010** [comment] 2016-09-18 17:34
@ivpusic 
Okay, I just tried what is suggested in #61 but now, I'm getting the following error
Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib

**Comment by ivpusic** [comment] 2016-09-18 17:49
my recommendation is to use cocoa pods to install dependencies. Check readme

**Comment by jo2010** [comment] 2016-09-18 18:48
@ivpusic I'm not sure if I understood the steps you mentioned in #61. What does the lines in bold means? Add those back?

"go to project General tab, scroll down to Embedded binaries. You will see that there are two pre-built frameworks. You can remove them, build project for Device => this will produce Frameworks built for Device platform. **Click + under Embedded binaries, and now you can add these two framework**"

This is how mine looks before I archive. Is this correct?
<img width="725" alt="screen shot 2016-09-18 at 11 46 42 am" src="https://cloud.githubusercontent.com/assets/20960548/18618166/b27b35c4-7d95-11e6-98ef-e51bacd58102.png">

**Comment by ivpusic** [comment] 2016-09-18 19:00
you have to add it to Embedded binaries section in order to work on real device

**Comment by jo2010** [comment] 2016-09-18 20:51
@ivpusic I think that's what I did earlier. I added them back, if I add them back I'm getting the same following error again while uploading using application loader. 
RSKImageCropper.framework contains unsupported architectures '[x86_64, i386]

This is how it looks now. Is this correct? 
<img width="689" alt="screen shot 2016-09-18 at 1 47 51 pm" src="https://cloud.githubusercontent.com/assets/20960548/18619006/c00f7554-7da6-11e6-8757-42120c95d5c2.png">

**Comment by ivpusic** [comment] 2016-09-18 21:07
https://github.com/ivpusic/react-native-image-crop-picker#non-cocoapods-users-1 check steps from here

**Comment by skvaghasiya** [comment] 2017-05-01 07:26
@ivpusic i have a got error.
please check this question - http://stackoverflow.com/questions/43680933/payumoney-sdk-framework-contains-unsupported-architectures-x86-64-i386

please help me.

**Comment by ekinburak** [comment] 2018-12-20 17:35
Alright, I found solution. But it does not properly. I believe we can fix it all together. 
Add a Run Script step to your "Build Phases", put it after your step to embed frameworks, set it to use /bin/sh and enter the following script. 

This script loops through the frameworks embedded in the application and removes unused architectures.

    APP_PATH="${TARGET_BUILD_DIR}/${WRAPPER_NAME}"
    find "$APP_PATH" -name '*.framework' -type d | while read -r FRAMEWORK
    do
        FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
        FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
        echo "Executable is $FRAMEWORK_EXECUTABLE_PATH"

    EXTRACTED_ARCHS=()

    for ARCH in $ARCHS
    do
        echo "Extracting $ARCH from $FRAMEWORK_EXECUTABLE_NAME"
        lipo -extract "$ARCH" "$FRAMEWORK_EXECUTABLE_PATH" -o "$FRAMEWORK_EXECUTABLE_PATH-$ARCH"
        EXTRACTED_ARCHS+=("$FRAMEWORK_EXECUTABLE_PATH-$ARCH")
    done
    echo "Merging extracted architectures: ${ARCHS}"
    lipo -o "$FRAMEWORK_EXECUTABLE_PATH-merged" -create "${EXTRACTED_ARCHS[@]}"
    rm "${EXTRACTED_ARCHS[@]}"

    echo "Replacing original executable with thinned version"
    rm "$FRAMEWORK_EXECUTABLE_PATH"
    mv "$FRAMEWORK_EXECUTABLE_PATH-merged" "$FRAMEWORK_EXECUTABLE_PATH"
    done

Here is the [reference link](http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/) for the script. 

After this script project runs on a simulator as expected; however, it does not work on a device. Also, this script changes framework's team on the process of archiving. Can we try to keep their team ?
