### ISSUE TITLE
openCamera freezes on photo preview screen after canceling crop

### ISSUE THREAD

**Issue by tyleralves** [ivpusic/react-native-image-crop-picker#367] opened 2017-07-09 02:51 UTC
Looks like the new feature that allows you to stay in the camera after canceling a crop doesn't work for `openCamera`

### Version
- react-native-image-crop-picker: v0.14.1
- react-native v0.42.0

### Platform
- iOS

### Expected behaviour
Clicking `Cancel` on the cropper should take you back to functioning photo preview screen.

### Actual behaviour
The cropper closes properly, but the resulting photo preview screen is frozen.

### Steps to reproduce

1. Use `openCamera` with `cropping: true`

2. Take Photo (Camera) -> Use Photo (Photo Preview) -> Cancel (Cropper)

3. Delivered back to the Photo Preview screen but it is frozen

### Attachments

// stacktrace or any other useful debug info

**Comment by ivpusic** [comment] 2017-07-17 14:46
do you have some time to take a look into this, and submit PR?

**Comment by tyleralves** [comment] 2017-07-19 21:09
I can take a look in the next few day.

**Comment by Lexiwu** [comment] 2017-07-20 07:50
same problem for me. It just freezed after pressing cancel.

**Version**
react-native-image-crop-picker: v0.14.1
react-native v0.44.3

**Platform**
iOS

**Comment by imbudhiraja** [comment] 2017-08-03 12:55
ame problem for me. It just freezed after pressing cancel.

Version
react-native-image-crop-picker: v0.14.1
react-native v0.45.2

Platform
iOS

**Comment by jinxac** [comment] 2017-08-07 13:06
same problem for me. It just freezes after pressing cancel.

Version
react-native-image-crop-picker: v0.14.3
react-native v0.40

**Comment by jinxac** [comment] 2017-08-10 10:16
I was debugging this a little. Looks like main thread is getting blocked somehow. One of the possible scenario can be that dispatch is getting called on same thread.

**Comment by Jobeso** [comment] 2017-08-18 13:09
I got the same issue. It just freezes the whole app after pressing cancel.
Good hint @jinxac maybe a good trace so we can find out more about that.

**Comment by mehdijjz** [comment] 2017-08-23 05:33
I'm uninstalling this package because of this open issue

**Comment by jinxac** [comment] 2017-08-23 12:04
@mehdijjz I was close to release so I cloned the project and close the camera itself on pressing cancel. It is a hack but still a better user experience.

**Comment by Jobeso** [comment] 2017-08-23 13:01
@jinxac could you provide this version or create a PR?

**Comment by luco** [comment] 2017-08-24 14:39
+1 on this

**Comment by jinxac** [comment] 2017-08-25 08:12
@Jobeso I am not sure if thats the perfect solution so creating a PR wont be of much use. Here is the code for your reference. Change following in ImageCropPicker.m

```
- (void) dismissCropper:(RSKImageCropViewController*) controller dismissAll: (BOOL) dissmissAll completion:(void (^)())completion {
    //We've presented the cropper on top of the image picker as to not have a double modal animation.
    //Thus, we need to dismiss the image picker view controller to dismiss the whole stack.
    if (!self.cropOnly) {
        if (dissmissAll) {
            UIViewController *topViewController = controller.presentingViewController.presentingViewController;
            [topViewController dismissViewControllerAnimated:YES completion:completion];
        } else {
            **// FIX: On landing on camera from retake app freezes so closing camera for now**
            UIViewController *topViewController = controller.presentingViewController.presentingViewController;
            // UIViewController *topViewController = controller.presentingViewController;
            [topViewController dismissViewControllerAnimated:YES completion:completion];
        }
    } else {
        [controller dismissViewControllerAnimated:YES completion:completion];
    }
}
```

**Comment by Jobeso** [comment] 2017-08-25 13:54
@jinxac yeah you are right, thank you for this code

**Comment by luco** [comment] 2017-08-29 12:21
@jinxac This works perfectly. You should send a PR.

**Comment by SainiRohitSeasia** [comment] 2017-08-31 08:42
Hello,  there's a issue.Code works fine, but i am unable to open camera again after cancel.

**Comment by jinxac** [comment] 2017-08-31 11:58
@SainiRohitSeasia I am using this in production and it works fine for me

**Comment by SainiRohitSeasia** [comment] 2017-08-31 12:03
@jinxac I just replace your code with the existing code in ImageCropPicker.m file.And after that i am facing this issue.

**Comment by jinxac** [comment] 2017-08-31 12:05
Interesting. Can you share your use case? How are u using the component?

**Comment by mehdijjz** [comment] 2017-09-12 07:35
any updates on this ?

**Comment by yeajig** [comment] 2017-09-13 07:56
same problem for me,@jinxac yeah you are right, thank you for this code

**Comment by efstathiosntonas** [comment] 2017-09-15 12:29
@jinxac thanks for the code, there's a typo, you should remove the `**` before `else {
            **// FIX: On landing` otherwise xcode complains about not finding `topViewController` class.

**Comment by TakaGoto** [comment] 2017-09-22 14:27
+1

**Comment by JulienBerge** [comment] 2017-09-25 18:28
+1

**Comment by ivpusic** [comment] 2017-09-27 18:30
fixed in version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.17.0

**Closed by ivpusic** 2017-09-27 18:30 UTC

**Comment by grin** [comment] 2017-10-02 21:45
@ivpusic Thanks for fixing that, my app no longer freezes but it now quits the whole openCamera flow. Is this expected behavior? I think, ideally, after clicking cancel when cropping a photo, it should take you back to functioning photo preview screen. 

Is this possible? Any pointers how it can be done?

**Comment by SudoPlz** [comment] 2021-05-13 22:16
Maybe related to https://github.com/ivpusic/react-native-image-crop-picker/issues/1585
