### ISSUE TITLE
Having trouble with install/build 

### ISSUE THREAD

**Issue by pcompassion** [ivpusic/react-native-image-crop-picker#90] opened 2016-09-29 00:45 UTC
We are unable to build android app with the library.

### Version
- react-native-image-crop-picker v0.9.5
- react-native v0.34.0
- react-anative-video v0.9.0

### Platform
- Android

### Expected behaviour
Build and run react-native + react-native-image-crop-picker as an activity on our existing project

### Actual behaviour

(Attachment #1 at the bottom)
 FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':littleHome:transformClassesWithJarMergingForDebugJihae'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class

### Steps to reproduce
1. build.gradle:
    compile 'com.facebook.react:react-native:+'
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-video')

 Build failed=>ZipException: duplicate entry: okio/AsyncTimeout$1.class

2. in order to get rid of java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class error
We removed okio from some of our components in our build.gradle

****build.gradle:app
   ...
    compile 'com.facebook.react:react-native:+'
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-video')
}
+  configurations {
+    compile.exclude module: 'okio'
+ }

3. From one of our fragment, we initiated the SampleActivity (https://github.com/ivpusic/react-native-image-crop-picker/blob/master/example/android/app/src/main/java/com/example/MainActivity.java)
Intent intent = new Intent(this.mActivity, SampleActivity.class);
mThreadInputFragment.startActivity(intent);

4. react-native start
5. run

On start up of the sample activity, app dies with the following error
(complete stacktrace is at # attachement 2 at the bottom)

E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
 java.lang.NoSuchMethodError: No interface method read([BII)I in class Lokio/BufferedSource; or its super classes (declaration of 'okio.BufferedSource' appears in /data/app/com.zibann.littlehome.debugjihae-1/base.apk:classes2.dex)

### build.gradle:app

apply plugin: 'android'
apply plugin: 'io.fabric'
apply plugin: "com.android.application"

import com.android.build.OutputFile
apply from: "../../momsite/node_modules/react-native/react.gradle"

android {
    compileSdkVersion 23
    buildToolsVersion 23.0.1
	useLibrary  'org.apache.http.legacy'
    defaultConfig {
        applicationId "com.zibann.littlehome"
        minSdkVersion 16
		targetSdkVersion 23
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

    splits {
        abi {
            reset()
            enable false//enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
	    minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            resValue "string", "searchSuggestionAuthority", "com.zibann.littlehome.provider.SearchSuggestionProvider"
            signingConfig signingConfigs.releaseConfig;
        }

        debugRelease {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            resValue "string", "searchSuggestionAuthority", "com.zibann.littlehome.provider.SearchSuggestionProvider"
            signingConfig signingConfigs.debug
            debuggable true
        }
    }

    sourceSets.debugRelease.setRoot('src/debugRelease')
    packagingOptions {
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/jersey-module-version'
        exclude 'META-INF/ASL2.0'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
    }
    productFlavors {
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':externals:photoViewer')
    compile project(':MaterialSearchView')
    compile 'com.android.support:support-v4:20.+'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.android.support:design:24.2.1'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile files('libs/acra-4.5.0.jar')
    compile files('libs/androidasync-1.2.6.jar')
    compile files('libs/ion-1.2.7.jar')
    compile 'com.github.rampo.updatechecker:library:2.1.8'
    compile 'com.mcxiaoke.volley:library:1.0.+'
    compile 'com.viewpagerindicator:library:2.4.1@aar'
    compile 'com.squareup:otto:1.3.5'
    compile files('libs/naveroauthlib-4.1.1.jar')
    compile('com.facebook.android:facebook-android-sdk:4.1.0') {
        exclude module: 'bolts-android'
    }
    compile 'com.parse.bolts:bolts-applinks:1.3.0'
    compile 'com.kakao.sdk:usermgmt:1.0.50'
    compile 'com.kakao.sdk:kakaolink:1.0.50'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.android.support:design:23.0.0'
    compile 'com.google.guava:guava:11.0.2'
    compile 'commons-io:commons-io:+'
    compile 'io.branch.sdk.android:library:1.+'
    compile 'com.mixpanel.android:mixpanel-android:4.6.4'
    compile('com.crashlytics.sdk.android:answers:1.3.6@aar') {
        transitive = true;
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile 'com.melnykov:floatingactionbutton:1.3.0'
    compile 'com.facebook.react:react-native:+'
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-video')
}
 configurations {
     compile.exclude module: 'okio'
}

task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

### Attachments 1
Error:18:15:54.768 [ERROR] [system.err] Note: Some input files use or override a deprecated API.
18:15:54.769 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
18:15:54.770 [ERROR] [system.err] Note: Some input files use unchecked or unsafe operations.
18:15:54.770 [ERROR] [system.err] Note: Recompile with -Xlint:unchecked for details.
18:16:01.364 [ERROR] [org.gradle.BuildExceptionReporter]
18:16:01.364 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
18:16:01.365 [ERROR] [org.gradle.BuildExceptionReporter]
18:16:01.365 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
18:16:01.365 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':littleHome:transformClassesWithJarMergingForDebugJihae'.
18:16:01.365 [ERROR] [org.gradle.BuildExceptionReporter] > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class
18:16:01.365 [ERROR] [org.gradle.BuildExceptionReporter]
18:16:01.365 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
18:16:01.366 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':littleHome:transformClassesWithJarMergingForDebugJihae'.
18:16:01.366 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
18:16:01.366 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
18:16:01.366 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
18:16:01.367 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
18:16:01.367 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
18:16:01.367 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
18:16:01.367 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
18:16:01.367 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
18:16:01.367 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
18:16:01.368 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
18:16:01.368 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
18:16:01.368 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
18:16:01.368 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
18:16:01.368 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
18:16:01.368 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
18:16:01.369 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
18:16:01.369 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
18:16:01.369 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
18:16:01.369 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
18:16:01.369 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
18:16:01.369 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
18:16:01.370 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
18:16:01.370 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
18:16:01.370 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Factories$1.create(Factories.java:22)
18:16:01.370 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
18:16:01.370 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
18:16:01.370 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
18:16:01.371 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
18:16:01.371 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
18:16:01.371 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
18:16:01.371 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
18:16:01.371 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
18:16:01.371 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
18:16:01.372 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
18:16:01.372 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
18:16:01.372 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
18:16:01.372 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
18:16:01.372 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
18:16:01.372 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
18:16:01.373 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
18:16:01.373 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
18:16:01.373 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
18:16:01.373 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
18:16:01.373 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
18:16:01.373 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:16:01.374 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.374 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
18:16:01.374 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.374 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
18:16:01.374 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.374 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
18:16:01.375 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.375 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
18:16:01.375 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
18:16:01.375 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
18:16:01.376 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
18:16:01.376 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.376 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
18:16:01.376 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.376 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
18:16:01.376 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:16:01.377 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.377 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
18:16:01.377 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
18:16:01.377 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.377 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
18:16:01.377 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
18:16:01.378 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
18:16:01.378 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
18:16:01.378 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
18:16:01.378 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
18:16:01.379 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class
18:16:01.379 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
18:16:01.379 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:158)
18:16:01.379 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
18:16:01.379 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
18:16:01.379 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
18:16:01.380 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
18:16:01.380 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
18:16:01.380 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
18:16:01.380 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
18:16:01.380 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
18:16:01.380 [ERROR] [org.gradle.BuildExceptionReporter] 	... 70 more
18:16:01.381 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class
18:16:01.381 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.JarMergingTransform.transform(JarMergingTransform.java:118)
18:16:01.381 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter] 	... 78 more
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.JarMerger.addJar(JarMerger.java:191)
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.JarMerger.addJar(JarMerger.java:150)
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.android.build.gradle.internal.transforms.JarMergingTransform.transform(JarMergingTransform.java:108)
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter] 	... 81 more
18:16:01.390 [ERROR] [org.gradle.BuildExceptionReporter]

### Attachments 2
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
 java.lang.NoSuchMethodError: No interface method read([BII)I in class Lokio/BufferedSource; or its super classes (declaration of 'okio.BufferedSource' appears in /data/app/com.zibann.littlehome.debugjihae-1/base.apk:classes2.dex)
 at okhttp3.internal.ws.WebSocketWriter.writeMaskedSynchronized(WebSocketWriter.java:220)

at okhttp3.internal.ws.WebSocketWriter.writeMaskedSynchronized(WebSocketWriter.java:220)
at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:142)
at okhttp3.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:111)
at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:168)
at com.facebook.react.devsupport.JSPackagerWebSocketClient.closeWebSocketQuietly(JSPackagerWebSocketClient.java:104)
at com.facebook.react.devsupport.JSPackagerWebSocketClient.abort(JSPackagerWebSocketClient.java:196)
at com.facebook.react.devsupport.JSPackagerWebSocketClient.onFailure(JSPackagerWebSocketClient.java:168)
at okhttp3.internal.ws.RealWebSocket.readerErrorClose(RealWebSocket.java:217)
at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:100)
at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

**Comment by ivpusic** [comment] 2016-09-29 21:05
from error you posted I cannot see anything related to react-native-image-crop-picker. Can you please double check if the problem is really with react-native-image-crop-picker or something else. Will close this one for now

**Closed by ivpusic** 2016-09-29 21:05 UTC
