### ISSUE TITLE
run on android devices can not multiple

### ISSUE THREAD

**Issue by ywqian** [ivpusic/react-native-image-crop-picker#152] opened 2016-11-29 02:39 UTC
### Version
Tell us which versions you are using: 
- react-native-image-crop-picker v0.10.5
- react-native v0.38.0

### Platform
- Android

pickMultiple() {
        ImagePicker.openPicker({
            multiple: true
        }).then(images => {

            this.setState({
                image: null,
                images: images.map(i => {
                    console.log('received image', i);
                    return {uri: i.path, width: i.width, height: i.height, mime: i.mime};
                })
            });
        }).catch(e => alert(e));
    }

run on android device can not multiple pictures, why？

**Comment by ivpusic** [comment] 2016-11-30 08:44
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/122

**Closed by ivpusic** 2016-11-30 08:44 UTC
