### ISSUE TITLE
Link in RN 0.32 failed

### ISSUE THREAD

**Issue by jaggerwang** [ivpusic/react-native-image-crop-picker#60] opened 2016-09-04 14:04 UTC
### Version

- react-native-image-crop-picker v0.8.0
- react-native v0.32.0

### Expected behaviour

After installed npm package, `react-native link` should be ok.

### Actual behaviour

Get error:
```
rnpm-install info Linking react-native-image-crop-picker android dependency
rnpm-install ERR! It seems something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/jagger/projects/zaiqiuchang/app/android/app/src/main/java/com/zaiqiuchang/app/MainApplication.java'
Please file an issue here: https://github.com/rnpm/rnpm/issues

ENOENT: no such file or directory, open '/Users/jagger/projects/zaiqiuchang/app/android/app/src/main/java/com/zaiqiuchang/app/MainApplication.java'
```

There is no "app" in java package path, the correct path should be "android/app/src/main/java/com/zaiqiuchang/MainApplication.java".
![image](https://cloud.githubusercontent.com/assets/1255011/18231396/8fc59948-72eb-11e6-8f10-1d5bc4176637.png)

### Steps to reproduce

1. npm i react-native-image-crop-picker --save
2. react-native link react-native-image-crop-picker

**Comment by ivpusic** [comment] 2016-09-04 14:17
cannot reproduce this. Probably better place to fill this issue is rnpm page. 

I don't have knowledge how rnpm is resolving final path, but your project config is maybe somewhere including this wrong `app` prefix, which may instruct rnpm to make this decision.

**Closed by ivpusic** 2016-09-04 14:17 UTC
