### ISSUE TITLE
I can't select multiple pictures on android

### ISSUE THREAD

**Issue by zhanguangao** [ivpusic/react-native-image-crop-picker#142] opened 2016-11-16 09:27 UTC
"react-native-image-crop-picker": "^0.10.3",
"react-native": "^0.37.0",

ImagePicker.openPicker({
          multiple: true,
        }).then(images => {
            images.map(i => {
               this.imageList.push(i.path);
            });
            this.setState({
                dataSource:this.state.dataSource.cloneWithRows(this.imageList),
            });
        });

**Comment by ivpusic** [comment] 2016-11-16 09:36
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/122

**Closed by ivpusic** 2016-11-16 09:36 UTC
