### ISSUE TITLE
android  open   multiple: true  is noworking

### ISSUE THREAD

**Issue by xiaoxnn** [ivpusic/react-native-image-crop-picker#608] opened 2018-02-07 09:56 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.19.1
- react-native v0.46.4

### Platform

- Android 7.0

 ImagePicker.openPicker({
            multiple: true
        }).then(images => {
            console.log(images);
     });

By calling the above method, I just select a picture.

**Comment by ivpusic** [comment] 2018-02-07 10:10
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/607

**Closed by ivpusic** 2018-02-07 10:10 UTC

**Comment by xiaoxnn** [comment] 2018-02-07 10:33
I Just try long-pressing on image, but not  enter multiple-selection mode.

**Comment by ivpusic** [comment] 2018-02-07 10:50
then your device does not support it unfortunately. The package is using built-in image picker, and for some devices, multiple selections do not work.
