### ISSUE TITLE
[Android] Image seleted success but app has stoptted when confirm

### ISSUE THREAD

**Issue by zhuyunxiang** [ivpusic/react-native-image-crop-picker#139] opened 2016-11-14 09:16 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.2
- react-native v0.34.1

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
return img's detail data

### Actual behaviour
APP stopped

### Steps to reproduce

1. Choose image.

2. Click confirm button.

### Attachments

// stacktrace or any other useful debug info

**Comment by zhuyunxiang** [comment] 2016-11-14 09:18
The same code in IOS is OK

**Comment by ivpusic** [comment] 2016-11-14 09:32
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/122

**Closed by ivpusic** 2016-11-14 09:32 UTC
