### ISSUE TITLE
[Android] Error install version > 0.13.1

### ISSUE THREAD

**Issue by agumack** [ivpusic/react-native-image-crop-picker#387] opened 2017-07-26 04:19 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.14
- react-native v0.46.4

### Platform
- Android

### Expected behaviour

Hi all, I have issue when install 'react-native-image-crop-picker' version > 0.13.1 (Android Only)

> E/dalvikvm(17230): Could not find class 'com.facebook.react.shell.MainReactPackage$1', referenced from method com.facebook.react.shell.MainReactPackage.getNativeModules
E/dalvikvm(17230): Could not find class 'okhttp3.OkHttpClient$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.<init>
E/dalvikvm(17230): Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.enqueueOnChangeEndpointLongPolling
E/dalvikvm(17230): Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.downloadBundleResourceFromUrlSync
E/dalvikvm(17230): Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.isPackagerRunning
E/dalvikvm(17230): Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.launchJSDevtools
E/dalvikvm(17230): Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.openStackFrameCall
E/dalvikvm(17230): Could not find class 'okhttp3.OkHttpClient$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.startPollingOnChangeEndpoint
E/dalvikvm(17230): Could not find class 'okhttp3.Request$Builder', referenced from method com.facebook.react.devsupport.DevServerHelper.symbolicateStackTrace
E/AndroidRuntime(17230): FATAL EXCEPTION: main
E/AndroidRuntime(17230): Process: com.datingapp, PID: 17230
E/AndroidRuntime(17230): java.lang.RuntimeException: Unable to resume activity {com.datingapp/com.datingapp.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
E/AndroidRuntime(17230): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2798)
E/AndroidRuntime(17230): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2827)
E/AndroidRuntime(17230): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2255)
E/AndroidRuntime(17230): 	at android.app.ActivityThread.access$900(ActivityThread.java:141)
E/AndroidRuntime(17230): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
E/AndroidRuntime(17230): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17230): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(17230): 	at android.app.ActivityThread.main(ActivityThread.java:5072)
E/AndroidRuntime(17230): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(17230): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(17230): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime(17230): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
E/AndroidRuntime(17230): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(17230): Caused by: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
E/AndroidRuntime(17230): 	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:84)
E/AndroidRuntime(17230): 	at com.facebook.react.ReactInstanceManager.<init>(ReactInstanceManager.java:240)
E/AndroidRuntime(17230): 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:248)
E/AndroidRuntime(17230): 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:84)
E/AndroidRuntime(17230): 	at com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.createReactInstanceManager(NavigationReactGateway.java:145)
E/AndroidRuntime(17230): 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
E/AndroidRuntime(17230): 	at com.reactnativenavigation.react.NavigationReactGateway.getReactInstanceManager(NavigationReactGateway.java:59)
E/AndroidRuntime(17230): 	at com.reactnativenavigation.react.NavigationReactGateway.hasStartedCreatingContext(NavigationReactGateway.java:46)
E/AndroidRuntime(17230): 	at com.reactnativenavigation.controllers.SplashActivity.onResume(SplashActivity.java:28)
E/AndroidRuntime(17230): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
E/AndroidRuntime(17230): 	at android.app.Activity.performResume(Activity.java:5328)
E/AndroidRuntime(17230): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2788)
E/AndroidRuntime(17230): 	... 12 more
E/AndroidRuntime(17230): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(17230): 	at java.lang.reflect.Constructor.constructNative(Native Method)
E/AndroidRuntime(17230): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
E/AndroidRuntime(17230): 	at com.facebook.react.devsupport.DevSupportManagerFactory.create(DevSupportManagerFactory.java:76)
E/AndroidRuntime(17230): 	... 23 more
E/AndroidRuntime(17230): Caused by: java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder
E/AndroidRuntime(17230): 	at com.facebook.react.devsupport.DevServerHelper.<init>(DevServerHelper.java:122)
E/AndroidRuntime(17230): 	at com.facebook.react.devsupport.DevSupportManagerImpl.<init>(DevSupportManagerImpl.java:196)
E/AndroidRuntime(17230): 	... 26 more

**Comment by ivpusic** [comment] 2017-07-26 08:11
are you sure issue is related to this module?

**Comment by agumack** [comment] 2017-07-26 13:58
yep @ivpusic 
I am sure, i tried uninstall any modules using for detect bug. 
I also create a new react-native app (react-native init newapp) and have same problem with react-native-image-crop-picker version > 0.13.1

**Comment by agumack** [comment] 2017-07-27 17:30
@ivpusic Hope to be supported from you. thanks so much!

**Comment by ivpusic** [comment] 2017-08-01 13:24
I cannot reproduce the issue.

**Comment by ivpusic** [comment] 2017-09-27 18:52
closing this issue as I cannot reproduce it. Please let me know if you are still having problems with it.

**Closed by ivpusic** 2017-09-27 18:52 UTC
