### ISSUE TITLE
Call multiple image picker can only select one images!

### ISSUE THREAD

**Issue by wzy535** [ivpusic/react-native-image-crop-picker#69] opened 2016-09-11 02:05 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.8.2
- react-native v0.31.0
- simulator android 

### Expected behaviour
select multiple images

### Actual behaviour
only can select one images

### Steps to reproduce

1. use example " Call multiple image picker" code 
2.can only select one images

Thanks in advance!

**Comment by ivpusic** [comment] 2016-09-11 14:28
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/31

**Closed by ivpusic** 2016-09-11 14:28 UTC
