### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by ivanzhang** [ivpusic/react-native-image-crop-picker#2] opened 2016-05-27 03:51 UTC
i created Podfile with 
pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'
under iOS project and 
run 
pod install

got error:

[!] The dependency `react-native-image-crop-picker (from `../../node_modules/react-native-image-crop-picker/ios`)` is not used in any concrete target.

**Comment by ivpusic** [comment] 2016-05-30 14:21
cannot reproduce.

example podfile which works for me:

```
platform :ios, '8.0'

target 'picker' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
    pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'
end
```

**Comment by ivpusic** [comment] 2016-05-30 14:35
will close this one for now...if you still have issues with it, please reopen

**Closed by ivpusic** 2016-05-30 14:35 UTC

**Comment by MonFig** [comment] 2017-03-12 01:52
try to write your target in your podfile like this
```
platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'MyApp' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 2.3'
end
```
