### ISSUE TITLE
Nothing opens or shows on simulator

### ISSUE THREAD

**Issue by mitjnextt** [ivpusic/react-native-image-crop-picker#1383] opened 2020-08-25 11:19 UTC
HIi @ivpusic , I am facing this issue on iOS where nothing happens when clicking on the button, I have confirmed that button is being clicked and all other code is running but nothing with picker.
Some help would be appreciated! Thanks.

### Version

- react-native-image-crop-picker "^0.33.1"
- react-native "0.62.2"

### Platform

- iOS

### Expected behaviour

- Picker/Gallery should open up

### Actual behaviour

- Nothing opens up, and no logs in terminal

**Comment by standreinmcp** [comment] 2020-08-25 11:52
I get the same behaviour

**Comment by christiandrey** [comment] 2020-08-25 13:33
Have you tried downgrading to react-native-image-crop-picker@0.33.0? It worked for me.

**Comment by ktomi42** [comment] 2020-08-25 15:20
@mitjnextt did you have the following when you run pod install?

[!] [Xcodeproj] Generated duplicate UUIDs:

PBXFileReference -- Pods.xcodeproj/mainGroup/children/children:children:|,|,|,|,|,displayName:CocoaAsyncSocket,isa:PBXGroup,name:CocoaAsyncSocket,path:CocoaAsyncSocket,sourceTree:,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:CocoaLibEvent,isa:PBXGroup,name:CocoaLibEvent,path:CocoaLibEvent,sourceTree:,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:DoubleConversion,isa:PBXGroup,name:DoubleConversion,path:DoubleConversion,sourceTree:,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Flipper,isa:PBXGroup,name:Flipper,path:Flipper,sourceTree:,,children:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,displayName:Flipper-DoubleConversion,isa:PBXGroup,name:Flipper-DoubleConversion, ...

**Comment by standreinmcp** [comment] 2020-08-25 15:59
@ktomi42 Yes! Also, @christiandrey I tried downgrading, still not working

**Comment by ktomi42** [comment] 2020-08-25 16:01
@standreinmcp it seems the problem is with 
s.dependency 'TOCropViewController'

check this out:
https://github.com/ivpusic/react-native-image-crop-picker/issues/1359#issuecomment-666333218

**Comment by christiandrey** [comment] 2020-08-25 16:03
@standreinmcp Just to make sure, did you follow these steps:

1. Uninstall react-native-image-crop-picker@0.33.1
2. Do `pod install` in the `ios` folder
3. Install react-native-image-crop-picker@0.33.0
4. Do `pod install` again in the `ios` folder

**Comment by DaneEveritt** [comment] 2020-08-25 16:07
I can confirm I was having the same issue on `0.33.1` and reverting to `0.33.0` has fixed it for me.

I noticed it wouldn't open until I edited a few things on the form it was in, but honestly I don't know enough about the deep internals of how this stuff works to be able to provide much more than "it didn't work until I typed some text in two fields and then it would work fine."

I did have it opening from within a deep navigation screen in a stack navigator modal if that helps at all.

**Comment by standreinmcp** [comment] 2020-08-25 16:10
@christiandrey It worked! Yeah, I had to redo the install with the 0.33 version. Thanks!

**Comment by DemaHamson** [comment] 2020-08-26 02:13
help!
react-native "0.63.2"
react-native-image-crop-picker "^0.33.1" no work,  down to "^0.33.0" still no work

**Comment by DaneEveritt** [comment] 2020-08-26 04:07
`^0.33.0` will install `0.33.1`, you need to have it fixed at `0.33.0` (remove the caret, `^`, before installing).

**Comment by ivpusic** [comment] 2020-08-26 07:07
fixed in https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.33.2

**Closed by ivpusic** 2020-08-26 07:07 UTC

**Comment by mitjnextt** [comment] 2020-08-26 11:58
Thank you @ivpusic and everyone

**Comment by mitjnextt** [comment] 2020-08-26 12:06
> I can confirm I was having the same issue on `0.33.1` and reverting to `0.33.0` has fixed it for me.
> 
> I noticed it wouldn't open until I edited a few things on the form it was in, but honestly I don't know enough about the deep internals of how this stuff works to be able to provide much more than "it didn't work until I typed some text in two fields and then it would work fine."
> 
> I did have it opening from within a deep navigation screen in a stack navigator modal if that helps at all.
> 
> As for the Podfile warnings, I just added this to my Podfile. The linked issue is where I found this.
> 
> ```
> # @see https://github.com/ivpusic/react-native-image-crop-picker/issues/680
> install! 'cocoapods', :deterministic_uuids => false
> ```

Thanks @DaneEveritt 
I was facing that `Generated duplicate UUIDs` warning while pod install too and this code helped
