### ISSUE TITLE
Cannot select multiple images in android!

### ISSUE THREAD

**Issue by ankitbisht143** [ivpusic/react-native-image-crop-picker#475] opened 2017-10-15 13:44 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker 0.17.2
- react-native 0.48.4

### Platform
Tell us to which platform this issue is related

- Android

I am using android 5.0.2 micromax but I am not able to select multiple images in android. Its working fine in IOS but not in android.
By long press also, its not working.

**Comment by ivpusic** [comment] 2017-10-16 09:23
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/417

**Closed by ivpusic** 2017-10-16 09:23 UTC
