### ISSUE TITLE
Android video select 

### ISSUE THREAD

**Issue by fendorio** [ivpusic/react-native-image-crop-picker#440] opened 2017-09-11 19:38 UTC
### Version

- react-native-image-crop-picker v0.16.0
- react-native v0.47.2

### Platform

- Android

### Expected behaviour

Documentation to state that the property 'cropping' set to true, will result in video selection not working on Android, alternatively, video selection to work if the property 'cropping' is set to true, just the same as IOS.

### Actual behaviour

Setting the property 'cropping' to true on Android results in no videos being presented, just images when using:

```
       ImagePicker.openPicker({
            multiple: true,
            mediaType: "video",
            cropping: true
        })
```

### Steps to reproduce

1. Initialise the image picker using the following method:

```
        ImagePicker.openPicker({
            multiple: true,
            mediaType: "video",
            cropping: true
        })
```

2. Observe what files are presented from the file selection intent. No videos should be presented.

3. Now compare with the following initialisation call

```
        ImagePicker.openPicker({
            multiple: true,
            mediaType: "video"
        })
```

4. You should see videos presented in the file selection intent.
### Attachments

N/A

**Comment by fendorio** [comment] 2017-09-11 19:39
Happy to contribute to the documentation, please advise if you'd wish me to add this caveat on Android to the docs.

**Comment by ivpusic** [comment] 2017-09-11 21:18
Yes, please. Thanks

**Comment by fendorio** [comment] 2017-09-11 21:44
PR sent.

**Comment by ivpusic** [comment] 2017-09-11 23:08
pr merged

**Closed by ivpusic** 2017-09-11 23:08 UTC

**Comment by imbudhiraja** [comment] 2017-10-03 10:42
Hi @ivpusic 
this issue still exists . 

Here are steps to reproduce it .

1. ImagePicker.openPicker({
            multiple: true,
            mediaType: "photo",
            cropping: true
        })

Open picker with cropping features.

2. Now open video picker with below details
 ImagePicker.openPicker({
    multiple: true,
    mediaType: "video",
})

3. It will redirect you to photo library instead of video. It happens due to the cropping variable. once its value set to true it always return true when you go from video gallery. Don't no way this happen.

https://github.com/ivpusic/react-native-image-crop-picker/blob/master/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java

Thanks.

**Comment by fendorio** [comment] 2017-10-03 10:49
@imbudhiraja This PR relates to documentation, the documentation now gives an example of how you should use the library to retrieve videos.

**Comment by akyker20** [comment] 2018-01-15 17:15
I found a work around to solve @ivpusic issue where if you open ImagePicker with mediaType: 'photo' and then open with mediaType: 'video', you can't select videos.

Set `cropping: false` when you open ImagePicker to show videos!
