### ISSUE TITLE
Unable to select multiple images/ videos from gallery in Android

### ISSUE THREAD

**Issue by kviswanath** [ivpusic/react-native-image-crop-picker#117] opened 2016-10-19 19:12 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.8.3
- react-native v0.32

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

Passing attribute "multiple" should allow selection of multiple images and videos before returning to the app.

### Actual behaviour

Passing attributes "multiple" and "maxFiles" does not work. The gallery closes after selecting a single image from the gallery.

### Steps to reproduce
`
  ImagePicker.openPicker({
      multiple: true,
      maxFiles: 5
    }).then(images => {
      for(image in images){
      }
    });
`

**Comment by ivpusic** [comment] 2016-10-19 20:24
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/31

**Closed by ivpusic** 2016-10-19 20:24 UTC

**Comment by kviswanath** [comment] 2016-10-20 02:42
Thank you @ivpusic . I think the maxFiles attribute doesn't work for Android. Please correct me if I am wrong.

I am trying to build this on Nexus 5 and it did not work on the GenyMotion simulator. I will try and check if the behavior is different on the phone vs simulator.

Is there an another way where we can bring up a custom view to enable multiple selection in the gallery?

**Comment by ivpusic** [comment] 2016-10-20 06:17
currently maxFiles is ios only. Multiple selection shpuld work on newer androids
