### ISSUE TITLE
Crash when  Huawei T1（T1-701u）and oppo R7s take photo and try to select

### ISSUE THREAD

**Issue by litingjun2015** [ivpusic/react-native-image-crop-picker#207] opened 2017-01-19 03:01 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v3.10.8
- react-native v0.39.2

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour

take picture and choose

### Actual behaviour

take picture, choose and crash

### Steps to reproduce

1.take picture

2.choose

3.crash

### Attachments

// stacktrace or any other useful debug info

```
E/SprdOEMCamera(  201): *********************Take picture statistic*******Start******************
E/SprdOEMCamera(  201):          takepicture,          0
E/SprdOEMCamera(  201):        capture start,          5
E/SprdOEMCamera(  201):          capture end,        312
E/SprdOEMCamera(  201):         rotate start,        312
E/SprdOEMCamera(  201):           rotate end,        327
E/SprdOEMCamera(  201):         review start,        327
E/SprdOEMCamera(  201):           review end,        327
E/SprdOEMCamera(  201):           system lag,        350
E/SprdOEMCamera(  201):       jpeg enc start,        350
E/SprdOEMCamera(  201):         jpeg enc end,        371
E/SprdOEMCamera(  201):      thumb enc start,        372
E/SprdOEMCamera(  201):        thumb enc end,        374
E/SprdOEMCamera(  201):     write exif start,        374
E/SprdOEMCamera(  201):       write exif end,        375
E/SprdOEMCamera(  201):            call back,        375
E/SprdOEMCamera(  201): *********************Take picture statistic********End*******************
E/SprdOEMCamera(  201): L 9626, camera_post_capture_complete_msg: ret=0
E/CAMERA3_FlashParameter(10607): setFlashMode the value is not Supported:off
E/PowerManagerService(  688): Wake Locks: size=1
E/PowerManagerService(  688):   SCREEN_BRIGHT_WAKE_LOCK        'WindowManager' ON_AFTER_RELEASE (uid=1000, pid=688, ws=WorkSource{10050})
E/audio_hw_primary(  201): select_devices_signal starting... adev->out_devices 0x2 adev->in_devices 0x0
E/SprdCameraHardware(  201): Preview not in progress! stopPreviewInternal X
E/SprdCameraHardware(  201): Preview not in progress! stopPreviewInternal X
E/SprdOEMCamera(  201): L 9672, camera_cap_sub2_thread_proc: message.msg_type 0x200201, sub-type 0x0
E/SprdCameraHardware(  201): setPreviewWindow X preview window is NULL!
E/isp-video(  201): ISP_RAW: id:0x00, 01054 line, stopispserver : ISP_TOOL:stopispserver
E/isp-video(  201): ISP_RAW: id:0x00, 00971 line, ispserver_thread : ISP_TOOL:accept error Invalid argument
E/dalvikvm(13006): heapsize Dalvik_dalvik_system_VMRuntime_nativeMinimumHeapSize 4194304
E/dalvikvm(13006): heapsize dvmMinimumHeapSize 4194304
E/dalvikvm(13006): heapsize dvmMinimumHeapSize set minimumSize 4194304
E/dalvikvm(13006): heapsize Dalvik_dalvik_system_VMRuntime_nativeMinimumHeapSize 4194304
E/dalvikvm(13006): heapsize dvmMinimumHeapSize 4194304
E/dalvikvm(13006): heapsize dvmMinimumHeapSize set minimumSize 4194304
E/dalvikvm(10607): heapsize Dalvik_dalvik_system_VMRuntime_nativeMinimumHeapSize 4194304
E/dalvikvm(10607): heapsize dvmMinimumHeapSize 4194304
E/dalvikvm(10607): heapsize dvmMinimumHeapSize set minimumSize 4194304
E/dalvikvm(10607): heapsize Dalvik_dalvik_system_VMRuntime_nativeMinimumHeapSize 0
E/dalvikvm(10607): heapsize dvmMinimumHeapSize 0
E/dalvikvm(10607): heapsize dvmMinimumHeapSize set minimumSize 0
E/EmptyDevice(10607): EmptyDevice.onParameterChanged(UiDisplayEventParameter) was called.
E/VdcInflateDelegate(13006): Exception while inflating <vector>
E/VdcInflateDelegate(13006): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
E/VdcInflateDelegate(13006):   	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:541)
E/VdcInflateDelegate(13006):   	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:478)
E/VdcInflateDelegate(13006):   	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:441)
E/VdcInflateDelegate(13006):   	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:736)
E/VdcInflateDelegate(13006):   	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:359)
E/VdcInflateDelegate(13006):   	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:189)
E/VdcInflateDelegate(13006):   	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182)
E/VdcInflateDelegate(13006):   	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717)
E/VdcInflateDelegate(13006):   	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187)
E/VdcInflateDelegate(13006):   	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/VdcInflateDelegate(13006):   	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
E/VdcInflateDelegate(13006):   	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
E/VdcInflateDelegate(13006):   	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
E/VdcInflateDelegate(13006):   	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
E/VdcInflateDelegate(13006):   	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
E/VdcInflateDelegate(13006):   	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
E/VdcInflateDelegate(13006):   	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
E/VdcInflateDelegate(13006):   	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/VdcInflateDelegate(13006):   	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106)
E/VdcInflateDelegate(13006):   	at android.app.Activity.performCreate(Activity.java:5301)
E/VdcInflateDelegate(13006):   	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
E/VdcInflateDelegate(13006):   	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/VdcInflateDelegate(13006):   	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
E/VdcInflateDelegate(13006):   	at android.app.ActivityThread.access$1100(ActivityThread.java:143)
E/VdcInflateDelegate(13006):   	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
E/VdcInflateDelegate(13006):   	at android.os.Handler.dispatchMessage(Handler.java:102)
E/VdcInflateDelegate(13006):   	at android.os.Looper.loop(Looper.java:136)
E/VdcInflateDelegate(13006):   	at android.app.ActivityThread.main(ActivityThread.java:5398)
E/VdcInflateDelegate(13006):   	at java.lang.reflect.Method.invokeNative(Native Method)
E/VdcInflateDelegate(13006):   	at java.lang.reflect.Method.invoke(Method.java:515)
E/VdcInflateDelegate(13006):   	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/VdcInflateDelegate(13006):   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
E/VdcInflateDelegate(13006):   	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(13006): FATAL EXCEPTION: main
E/AndroidRuntime(13006): Process: com.duanglink.bizappv3, PID: 13006
E/AndroidRuntime(13006): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.duanglink.bizappv3/com.yalantis.ucrop.UCropActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f02004f
E/AndroidRuntime(13006):       	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2347)
E/AndroidRuntime(13006):       	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
E/AndroidRuntime(13006):       	at android.app.ActivityThread.access$1100(ActivityThread.java:143)
E/AndroidRuntime(13006):       	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
E/AndroidRuntime(13006):       	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(13006):       	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(13006):       	at android.app.ActivityThread.main(ActivityThread.java:5398)
E/AndroidRuntime(13006):       	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(13006):       	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(13006):       	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime(13006):       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
E/AndroidRuntime(13006):       	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(13006): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f02004f
E/AndroidRuntime(13006):       	at android.content.res.Resources.loadDrawable(Resources.java:2312)
E/AndroidRuntime(13006):       	at com.huawei.android.content.res.ResourcesEx.loadDrawable(ResourcesEx.java:660)
E/AndroidRuntime(13006):       	at android.content.res.Resources.getDrawable(Resources.java:774)
E/AndroidRuntime(13006):       	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
E/AndroidRuntime(13006):       	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:194)
E/AndroidRuntime(13006):       	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182)
E/AndroidRuntime(13006):       	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717)
E/AndroidRuntime(13006):       	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187)
E/AndroidRuntime(13006):       	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/AndroidRuntime(13006):       	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
E/AndroidRuntime(13006):       	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
E/AndroidRuntime(13006):       	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
E/AndroidRuntime(13006):       	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
E/AndroidRuntime(13006):       	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
E/AndroidRuntime(13006):       	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
E/AndroidRuntime(13006):       	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
E/AndroidRuntime(13006):       	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/AndroidRuntime(13006):       	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106)
E/AndroidRuntime(13006):       	at android.app.Activity.performCreate(Activity.java:5301)
E/AndroidRuntime(13006):       	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
E/AndroidRuntime(13006):       	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/AndroidRuntime(13006):       	... 11 more
E/AndroidRuntime(13006): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
E/AndroidRuntime(13006):       	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
E/AndroidRuntime(13006):       	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime(13006):       	at android.content.res.Resources.loadDrawable(Resources.java:2308)
E/AndroidRuntime(13006):       	... 31 more
E/SubmitMessage( 1444): Submit string: submit:trigger=0,bugtype=2,modulename=com.duanglink.bizappv3,level=1,testtype=NORMAL,path=/data/log/unzip/T1-701u_V100R001C233B006_R7L4C15615012251_20170117160851_crash
E/PackageLogInfoManager( 1444): checkPackageLogState, cr: android.app.ContextImpl$ApplicationContentResolver@418e7308, packageNames: null
E/PowerManagerService(  688): Wake Locks: size=0
```

Thanks.

**Comment by ivpusic** [comment] 2017-01-19 09:36
I don't have these devices, and therefore I cannot reproduce issue :/. Do you have some time to debug this?

**Comment by litingjun2015** [comment] 2017-01-20 01:36
recently i'm afraid not... I will be watching to decide the weight of this issue.

**Comment by ivpusic** [comment] 2017-01-23 20:42
could you try this? http://stackoverflow.com/questions/40323923/react-native-fatal-crash

**Comment by ivpusic** [comment] 2017-01-31 10:01
@litingjun2015 any updates?

**Comment by GalochkinKirov** [comment] 2017-02-01 08:35
I have same issue, but when choose a photo from local library with cropping.

**Comment by litingjun2015** [comment] 2017-02-07 03:32
@ivpusic , sorry for the late response.

http://stackoverflow.com/questions/34417843/how-to-use-vector-drawables-in-android-api-lower-21 says it's just a matter of upgrading your gradle version to 1.4.0-beta3 or higher
my gradle version is : 2.4

Another remedy could be:

```
static
{
    AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
}
```

-> where should I put this?

**Comment by ivpusic** [comment] 2017-02-07 09:56
try putting it into android MainActivity.java, and then run-android. Please let me know if this helped. Thanks for help.

**Comment by litingjun2015** [comment] 2017-02-08 06:44
tried, not work...

`E/VdcInflateDelegate(26999): Exception while inflating <vector>
E/VdcInflateDelegate(26999): org.xmlpull.v1.XmlPullParserException: Binary XML file line #17<vector> tag requires viewportWidth > 0
E/VdcInflateDelegate(26999):   	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:541)
E/VdcInflateDelegate(26999):   	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:478)
E/VdcInflateDelegate(26999):   	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:441)
E/VdcInflateDelegate(26999):   	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:736)
E/VdcInflateDelegate(26999):   	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:359)
E/VdcInflateDelegate(26999):   	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:189)
E/VdcInflateDelegate(26999):   	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182)
E/VdcInflateDelegate(26999):   	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717)
E/VdcInflateDelegate(26999):   	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187)
E/VdcInflateDelegate(26999):   	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/VdcInflateDelegate(26999):   	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
E/VdcInflateDelegate(26999):   	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
E/VdcInflateDelegate(26999):   	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
E/VdcInflateDelegate(26999):   	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
E/VdcInflateDelegate(26999):   	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
E/VdcInflateDelegate(26999):   	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
E/VdcInflateDelegate(26999):   	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
E/VdcInflateDelegate(26999):   	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/VdcInflateDelegate(26999):   	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106)
E/VdcInflateDelegate(26999):   	at android.app.Activity.performCreate(Activity.java:5301)
E/VdcInflateDelegate(26999):   	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
E/VdcInflateDelegate(26999):   	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/VdcInflateDelegate(26999):   	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
E/VdcInflateDelegate(26999):   	at android.app.ActivityThread.access$1100(ActivityThread.java:143)
E/VdcInflateDelegate(26999):   	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
E/VdcInflateDelegate(26999):   	at android.os.Handler.dispatchMessage(Handler.java:102)
E/VdcInflateDelegate(26999):   	at android.os.Looper.loop(Looper.java:136)
E/VdcInflateDelegate(26999):   	at android.app.ActivityThread.main(ActivityThread.java:5398)
E/VdcInflateDelegate(26999):   	at java.lang.reflect.Method.invokeNative(Native Method)
E/VdcInflateDelegate(26999):   	at java.lang.reflect.Method.invoke(Method.java:515)
E/VdcInflateDelegate(26999):   	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/VdcInflateDelegate(26999):   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
E/VdcInflateDelegate(26999):   	at dalvik.system.NativeStart.main(Native Method)
D/AndroidRuntime(26999): Shutting down VM
W/dalvikvm(26999): threadid=1: thread exiting with uncaught exception (group=0x41592c50)
E/AndroidRuntime(26999): FATAL EXCEPTION: main
E/AndroidRuntime(26999): Process: com.duanglink.bizappv3, PID: 26999
E/AndroidRuntime(26999): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.duanglink.bizappv3/com.yalantis.ucrop.UCropActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f02004f
E/AndroidRuntime(26999):       	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2347)
E/AndroidRuntime(26999):       	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
E/AndroidRuntime(26999):       	at android.app.ActivityThread.access$1100(ActivityThread.java:143)
E/AndroidRuntime(26999):       	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
E/AndroidRuntime(26999):       	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(26999):       	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(26999):       	at android.app.ActivityThread.main(ActivityThread.java:5398)
E/AndroidRuntime(26999):       	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26999):       	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(26999):       	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
E/AndroidRuntime(26999):       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
E/AndroidRuntime(26999):       	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(26999): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f02004f
E/AndroidRuntime(26999):       	at android.content.res.Resources.loadDrawable(Resources.java:2312)
E/AndroidRuntime(26999):       	at android.content.res.Resources.getDrawable(Resources.java:774)
E/AndroidRuntime(26999):       	at android.support.v7.widget.VectorEnabledTintResources.superGetDrawable(VectorEnabledTintResources.java:70)
E/AndroidRuntime(26999):       	at android.support.v7.widget.AppCompatDrawableManager.onDrawableLoadedFromResources(AppCompatDrawableManager.java:429)
E/AndroidRuntime(26999):       	at android.support.v7.widget.VectorEnabledTintResources.getDrawable(VectorEnabledTintResources.java:63)
E/AndroidRuntime(26999):       	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
E/AndroidRuntime(26999):       	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:194)
E/AndroidRuntime(26999):       	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182)
E/AndroidRuntime(26999):       	at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717)
E/AndroidRuntime(26999):       	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187)
E/AndroidRuntime(26999):       	at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
E/AndroidRuntime(26999):       	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
E/AndroidRuntime(26999):       	at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
E/AndroidRuntime(26999):       	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
E/AndroidRuntime(26999):       	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
E/AndroidRuntime(26999):       	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
E/AndroidRuntime(26999):       	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
E/AndroidRuntime(26999):       	at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
E/AndroidRuntime(26999):       	at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
E/AndroidRuntime(26999):       	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106)
E/AndroidRuntime(26999):       	at android.app.Activity.performCreate(Activity.java:5301)
E/AndroidRuntime(26999):       	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
E/AndroidRuntime(26999):       	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/AndroidRuntime(26999):       	... 11 more
E/AndroidRuntime(26999): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
E/AndroidRuntime(26999):       	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
E/AndroidRuntime(26999):       	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime(26999):       	at android.content.res.Resources.loadDrawable(Resources.java:2308)
E/AndroidRuntime(26999):       	... 33 more
W/ActivityManager(  686):   Force finishing activity com.duanglink.bizappv3/com.yalantis.ucrop.UCropActivity`

**Comment by ivpusic** [comment] 2017-02-28 11:30
@litingjun2015 could you try solution from here https://github.com/ivpusic/react-native-image-crop-picker/issues/214?

**Comment by ivpusic** [comment] 2017-03-03 00:49
@litingjun2015 this seems to be duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/256 which is now resolved. will close this one

**Closed by ivpusic** 2017-03-03 00:49 UTC

**Comment by litingjun2015** [comment] 2017-03-03 06:43
Thanks for your notification!

**Comment by litingjun2015** [comment] 2017-03-03 08:52
@ivpusic it works! thank you very much!!
