### ISSUE TITLE
Error when trying to do npm install with example project.

### ISSUE THREAD

**Issue by andrewheppner** [ivpusic/react-native-image-crop-picker#4] opened 2016-05-28 19:46 UTC
I am currently getting the following error on my machine when i clone your project and run npm install.

`npm WARN react-native-image-crop-picker@0.2.7 requires a peer of react-native@>=0.26.0 but none was installed.`

I have tried installing react-native and react globally but am still getting this error.

Any troubleshooting ideas?

**Comment by guyca** [comment] 2016-05-29 08:28
The log you've posted mentions an `npm warn` which shouldn't cause `npm install` to fail. AFAIK we don't have `react-native-image-crop-picker` as a dependency in both example projects.

What should work for you is cloning the repo and running `npm install` from `example-redux`.

**Comment by ivpusic** [comment] 2016-05-30 14:34
cannot reproduce this. I am using npm "3.6.0". warning is probably related to peerDependencies from package.json. Currently specified value is `>=0.26.0` so make sure you are using this version.

Will close this one for now.

**Closed by ivpusic** 2016-05-30 14:34 UTC
