### ISSUE TITLE
Build Android Failed

### ISSUE THREAD

**Issue by flaviotobi** [ivpusic/react-native-image-crop-picker#183] opened 2017-01-02 18:35 UTC
When i try to build android i get this error:
```
:react-native-image-crop-picker:compileReleaseJavaWithJavac
:react-native-image-crop-picker:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/ProjectName/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:47: error: PickerModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
/ProjectName/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:623: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
:react-native-image-crop-picker:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-crop-picker:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

In iOS works as expected.
### Version
- react-native-image-crop-picker 0.11.1
- react-native v0.31.0
### Platform
- Android

**Comment by ivpusic** [comment] 2017-01-03 11:53
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/50

**Closed by ivpusic** 2017-01-03 11:53 UTC
