### ISSUE TITLE
multiple images not work in android

### ISSUE THREAD

**Issue by greatzues** [ivpusic/react-native-image-crop-picker#122] opened 2016-10-26 14:53 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.1
- react-native v0.35.0

### Platform
Tell us to which platform this issue is related
- Android

### Expected behaviour
Expected able to  choice multiple images, return an array.

### Actual behaviour
> When I set `multiple: true`,I only get an array which  length is 1.In other words, I select an image it redirect immediately,only return an array with size of 1.

### Here is my code
```react-native
import ImagePicker from 'react-native-image-crop-picker';
export default class MyImagePicker extends Component {

    constructor(props) {
        super(props);
        this.state={
            src:'',
        }
    }

    pickSingle(){
        ImagePicker.openPicker({
            width: 300,
            height: 400,
            cropping: true
        }).then(image => {
            console.log(image);
            this.setState({
                src:image.path,
            })
        }).catch(e => {
            console.log('Error:'+e);
        });
    }

    pickMultiple(){
        ImagePicker.openPicker({
            multiple: true,
        }).then(images => {
            console.log(images);
        });
    }

    pickCamera(){
        ImagePicker.openCamera({
            width: 300,
            height: 400,
            cropping: true
        }).then(image => {
            console.log(image);
            this.setState({
                src:image.path,
            })
        });
    }

    pickClean(){
        ImagePicker.clean().then(() => {
            console.log('removed all tmp images from tmp directory');
        }).catch(e => {
            alert(e);
        });
    }

    render(){
        return(
            <View style={styles.container}>
                <TouchableOpacity onPress={this.pickMultiple.bind(this)}>
                    <View style={styles.button}>
                        <Text style={styles.text}>Image Picker Test</Text>
                    </View>
                </TouchableOpacity>
                {
                    this.state.src !== ''?<Image source={{uri:this.state.src}} style={{height:300, width:300}}/>:
                        <Image source={require('../img/UserDafault.png')} style={{height:300, width:300}}/>
                }
            </View>
        );
    }
}
```
### Attachments

// stacktrace or any other useful debug info
###  Everything seems to be ok but can not choose multiple images like run in ios.
![ios multiple images ](https://github.com/ivpusic/react-native-image-crop-picker/blob/master/images/ios_multiple_pick.png?raw=true)

**Comment by ivpusic** [comment] 2016-10-26 23:00
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/31

**Closed by ivpusic** 2016-10-26 23:00 UTC

**Comment by vic-tan** [comment] 2017-04-05 02:18
duplicate of #31 Not solve the problem

**Comment by pitamash** [comment] 2019-01-30 09:48
Use timeout to push images , I think that sorts out memory issue by pushing the images one by one at an interval 
```
this.imagePicker.getPictures({
        maximumImagesCount: 10,
        width:512,
        height:512,
        outputType: 1 ,
        quality:45
     }).then((results) => {
       for (var i = 0; i < results.length; i++) {
         if(results[i] ){
           let thisimg = {
               "src":'data:image/jpeg;base64,' + results[i] 
           };
           setTimeout(()=>{
            this.imageLists.push( thisimg );
           },1000) 
           //this.imageLists.reverse();
         } 
       }  
    }, (err) => { 
        this.events.publish("toast",err);
    });
```

**Comment by shakyarahul** [comment] 2020-03-19 05:33
in android you have to longPress on image to select multiple image
