### ISSUE TITLE
crash app when click confirm with android version < 5.0.0

### ISSUE THREAD

**Issue by tanmynguyen** [ivpusic/react-native-image-crop-picker#170] opened 2016-12-23 05:03 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.10.9
- react-native v0.3.9

### Platform
Tell us to which platform this issue is related

- Android

### Expected behaviour
don't crash app when confirm

### Actual behaviour
Has stoped app when comfirm after i take photo or choose library.
device android version < 5.0.0 -> has been crash
device android version >= 5.0.0 -> work :)

**Comment by ivpusic** [comment] 2016-12-23 21:40
tnx for reporting this. can you please attach stacktrace when crash happens? I tried on my android 4.x.x phones, and everything works ok.

**Comment by ivpusic** [comment] 2016-12-29 16:03
any updates here?

**Comment by gavin-gmlab** [comment] 2017-01-16 09:26
Hi,
   Got this same problem also. After picking the image, the app crashes

Platform: Android
Emulator: Android Studio
RN version: 39.2
Image crop picker version: 0.11.2
Android API version: 23

Emulator trace:
01-16 09:02:46.158 1538-1752/? I/ActivityManager: START u0 {act=android.intent.action.CHOOSER cmp=android/com.android.internal.app.ChooserActivity (has extras)} from uid 10058 on display 0
01-16 09:02:46.175 1538-2000/? I/ActivityManager: Start proc 18794:android:ui/1000 for activity android/com.android.internal.app.ChooserActivity
01-16 09:02:46.232 1538-1549/? I/ActivityManager: START u0 {act=android.intent.action.GET_CONTENT typ=image/* flg=0x3000000 cmp=com.android.documentsui/.DocumentsActivity (has extras)} from uid 10058 on display 0
01-16 09:02:46.282 17212-17225/? W/Documents: Failed to restore stack: java.io.FileNotFoundException: Failed to find matching root for null
01-16 09:02:46.342 17212-17229/? W/EGL_emulation: eglSurfaceAttrib not implemented
01-16 09:02:46.342 17212-17229/? W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa26da580, error=EGL_SUCCESS
01-16 09:02:46.467 17212-17225/? D/Documents: Before filtering 1, after 1
01-16 09:02:46.467 17212-17225/? D/Documents: Before filtering 2, after 1
01-16 09:02:46.467 17212-17225/? D/Documents: Found 2 of 2 recent queries done
01-16 09:02:46.618 1538-1557/? I/ActivityManager: Displayed com.android.documentsui/.DocumentsActivity: +360ms (total +454ms)
01-16 09:02:46.626 18715-18733/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xaadb17e0
01-16 09:02:46.660 17230-17245/? W/MediaProvider: original file hasn't been stored yet: /storage/emulated/0/Pictures/image-ca764cec-3705-479d-a03a-106ce9dacb6e2027651052.jpg
01-16 09:02:46.665 17230-17241/? V/MediaStore: Create the thumbnail in memory: origId=108, kind=1, isVideo=false
01-16 09:02:46.671 17230-17241/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:46.674 17230-17241/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:46.677 17230-17241/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:46.700 17212-17275/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:46.701 17212-17275/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:46.994 1538-1552/? I/ActivityManager: Killing 17959:com.android.development_settings/u0a26 (adj 15): empty #17
01-16 09:02:47.128 18715-18746/? W/unknown:React: StatusBarModule: Ignored status bar change, current activity is null.
01-16 09:02:53.276 17212-17275/? D/Documents: userMode=0, userSortOrder=0 --> mode=2, sortOrder=2
01-16 09:02:53.356 17230-17245/? W/MediaProvider: original file hasn't been stored yet: /storage/emulated/0/Pictures/image-ca764cec-3705-479d-a03a-106ce9dacb6e2027651052.jpg
01-16 09:02:53.365 17230-17242/? V/MediaStore: Create the thumbnail in memory: origId=108, kind=1, isVideo=false
01-16 09:02:53.373 17230-17242/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:53.376 17230-17242/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:53.377 17230-17242/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:53.387 17212-17275/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:53.387 17212-17275/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:55.021 17212-17275/? D/Documents: userMode=0, userSortOrder=0 --> mode=2, sortOrder=2
01-16 09:02:55.035 1199-1568/? D/AudioFlinger: mixer(0xb44c0000) throttle end: throttle time(223)
01-16 09:02:55.088 17230-17245/? W/MediaProvider: original file hasn't been stored yet: /storage/emulated/0/Pictures/image-ca764cec-3705-479d-a03a-106ce9dacb6e2027651052.jpg
01-16 09:02:55.094 17230-17276/? V/MediaStore: Create the thumbnail in memory: origId=108, kind=1, isVideo=false
01-16 09:02:55.102 17230-17276/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:55.103 17230-17276/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:55.106 17230-17276/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:55.124 17212-17275/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:55.125 17212-17275/? D/skia: --- SkImageDecoder::Factory returned null
01-16 09:02:57.548 1199-1568/? D/AudioFlinger: mixer(0xb44c0000) throttle end: throttle time(2)
01-16 09:02:57.553 17212-17212/? D/Documents: onFinished() [content://com.android.providers.media.documents/document/image%3A109]
01-16 09:02:57.642 1538-1752/? I/ActivityManager: START u0 {cmp=com.cqmrn/com.yalantis.ucrop.UCropActivity (has extras)} from uid 10058 on display 0
01-16 09:02:57.675 18715-18715/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-16 09:02:57.736 17212-17229/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa2650c20
01-16 09:02:57.745 17212-17229/? D/OpenGLRenderer: endAllStagingAnimators on 0xa1ed6f00 (GridView) with handle 0xa26bfb60
01-16 09:02:57.785 18715-18715/? D/BitmapLoadUtils: maxBitmapSize: 1411
01-16 09:02:57.787 18715-18730/? D/BitmapWorkerTask: Uri scheme: content
01-16 09:02:57.833 18715-18733/? W/EGL_emulation: eglSurfaceAttrib not implemented
01-16 09:02:57.833 18715-18733/? W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9f2ff180, error=EGL_SUCCESS
01-16 09:02:57.908 18715-18715/? D/TransformImageView: Image size: [167:84]
01-16 09:02:58.002 1538-1557/? I/ActivityManager: Displayed com.cqmrn/com.yalantis.ucrop.UCropActivity: +350ms (total +436ms)
01-16 09:02:58.135 17212-17212/? I/art: Starting a blocking GC Explicit
01-16 09:02:58.160 17212-17212/? I/art: Explicit concurrent mark sweep GC freed 3703(259KB) AllocSpace objects, 0(0B) LOS objects, 25% free, 2MB/2MB, paused 1.075ms total 23.379ms
01-16 09:02:58.199 17212-17212/? I/art: Starting a blocking GC Explicit
01-16 09:02:58.216 17212-17212/? I/art: Explicit concurrent mark sweep GC freed 6003(500KB) AllocSpace objects, 4(172KB) LOS objects, 24% free, 1568KB/2MB, paused 357us total 16.388ms
01-16 09:02:58.216 17212-17212/? I/art: Starting a blocking GC Explicit
01-16 09:02:58.247 17212-17212/? I/art: Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 24% free, 1568KB/2MB, paused 2.812ms total 31.364ms
01-16 09:03:04.433 18715-18730/? I/BitmapCropTask: Should crop: true
01-16 09:03:04.435 18715-18730/? D/uCrop JNI: Crop image with CImg
01-16 09:03:04.514 18715-18715/? D/image-crop-picker: Skipping image compression
01-16 09:03:04.516 18715-18745/? I/ReactNativeJS: { size: 9787,
                                                    mime: 'image/jpeg',
                                                    height: 84,
                                                    width: 63,
                                                    path: 'file:///data/user/0/com.xxxxx/cache/react-native-image-crop-picker/951478d9-a3be-487d-9c84-b517c305a787.jpg' }
01-16 09:03:04.590 18715-18733/? W/EGL_emulation: eglSurfaceAttrib not implemented
01-16 09:03:04.590 18715-18733/? W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x994933c0, error=EGL_SUCCESS
01-16 09:03:04.667 18715-18745/? I/ReactNativeJS: Running application "xxxxx" with appParams: {"initialProps":{},"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
01-16 09:03:04.683 18715-18733/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0x9f0ab290
01-16 09:03:04.685 1538-1557/? I/ActivityManager: Displayed com.xxxxx/.MainActivity: +198ms
01-16 09:03:04.703 18715-18745/? I/ReactNativeJS: Key splashScreen is already defined!

**Comment by ivpusic** [comment] 2017-01-16 09:34
hmm, could you send me image you selected, and give me exact steps how to reproduce this issue. This would be very helpful.

**Comment by gavin-gmlab** [comment] 2017-01-17 03:08
Not sure how you want to reproduce. The code I use is as follows:

  onActionsPress() {
    const options = [I18n.t('choose-picture'), I18n.t('take-picture'), I18n.t('cancel')]
    const cancelButtonIndex = options.length - 1;
    this.context.actionSheet().showActionSheetWithOptions({
      options,
      cancelButtonIndex,
    },
    (buttonIndex) => {
      switch (buttonIndex) {
        case 0:
          ImagePicker.openPicker({
              width: 300,
              height: 400,
              cropping: true
            }).then(image => {
              console.log(image);
              //this.props.onSend(image);
            });
          break;
        case 1:
          ImagePicker.openCamera({
            width: 300,
            height: 400,
            cropping: true
          }).then(image => {
            console.log(image);
            //this.props.onSend(image);
          });
          break;
        default:
      }
    });
  }

This is within an ActionSheet modal that pops up on the screen. I haven't tried the openCamera call yet, but the Cancel call works just fine to cancel the modal.
I see the image and can do the crop bit etc, but right after that the app crashes with no logs on what is happening. If in the crop screen I press cancel, I get this message then the app crashes:

01-16 10:45:33.269 18715-22755/? W/ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
                                                  User cancelled image selection
                                                  createErrorFromErrorData@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13925:20
                                                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:13888:59
                                                  __invokeCallback@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:14275:15
                                                  http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:14126:24
                                                  guard@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:14045:3
                                                  invokeCallbackAndReturnFlushedQueue@http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false:14125:6
                                                  invokeCallbackAndReturnFlushedQueue@[native code]

If I press the OK, the app also crashes as the 1st console log indicates.

**Comment by tanmynguyen** [comment] 2017-01-23 08:23
@ivpusic hi Bro. I have been crash app when use android version < 5.0. You can check in android version < 5.0??

**Comment by ivpusic** [comment] 2017-01-23 08:45
on my android < 5.0 devices it works. Would be very helpful if you can spend some time to debug it on your devices. Thanks

**Comment by tanmynguyen** [comment] 2017-01-23 08:50
I can't debug because app will be crash but not output error? so I known't error?

**Comment by ivpusic** [comment] 2017-01-23 09:25
you can get stacktrace from android studio

**Comment by gavin-gmlab** [comment] 2017-02-13 06:58
Not so familiar with getting stacktrace from Android. Is it just a matter of setting the --stacktrace and --debug options in the compiler settings? I looked at the output and it is almost what I have provided in my earlier console logs

**Comment by gavin-gmlab** [comment] 2017-02-13 10:55
An interesting finding today. The code that I have crashes on my Windows machine with android emulator, but doesn't crash on a Mac with the android emulator. Is there something on windows that the native code behaves differently from ?

**Comment by ivpusic** [comment] 2017-02-13 10:58
module does not contain any operating system specific code

**Comment by gavin-gmlab** [comment] 2017-02-14 04:52
OK, more findings. The module did not crash for the x64 emulator on Windows. So seems like the problem is with the 32 bit version.

**Comment by gavin-gmlab** [comment] 2017-02-22 09:00
@ivpusic Did you try on a 32 bit android emulator to see if you can duplicate this crashing?
![image](https://cloud.githubusercontent.com/assets/20513400/23204163/682d32d6-f920-11e6-8898-b484971240b8.png)

**Comment by ivpusic** [comment] 2017-02-22 09:28
tried it on exactly the same emulator and it is working for me. Can you try example project? Maybe we have different project configurations.

**Comment by gavin-gmlab** [comment] 2017-02-23 05:12
Downloaded the source and tried to run the example app as requested.

On the 64 bit emulator, works as expected. On the 32 bit emulator, the app didn't explicitly crash, but had the following logs in the console:

02-23 05:01:52.261 5005-5029/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7feecc31a0f0
02-23 05:01:52.265 1554-1578/? I/ActivityManager: Displayed com.example/com.yalantis.ucrop.UCropActivity: +2s254ms
02-23 05:01:52.368 4887-4901/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xea0faea0
02-23 05:01:58.249 4887-4951/? I/BitmapCropTask: Should crop: true
02-23 05:01:58.251 4887-4951/? D/uCrop JNI: Crop image with CImg
02-23 05:01:58.349 4887-4887/? D/image-crop-picker: Image compression activated
02-23 05:01:58.357 4887-4887/? D/image-crop-picker: Compressing image with quality 50.0
02-23 05:01:58.357 4887-4887/? D/image-crop-picker: Compressing image with max width 640
02-23 05:01:58.357 4887-4887/? D/image-crop-picker: Compressing image with max height 480
02-23 05:01:58.414 4887-4952/? I/ReactNativeJS: 'received image', { size: 1165,
                                                  mime: 'image/jpeg',
                                                  height: 49,
                                                  width: 49,
                                                  path: 'file:///storage/emulated/0/Pictures/991cf68e-51f6-444d-9fc5-d0877f15e2da.jpeg' }
02-23 05:01:59.057 4887-4901/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xea0f97e0
02-23 05:02:11.832 1186-1186/? I/ServiceManager: service 'SurfaceFlinger' died
02-23 05:02:11.832 1223-1816/? W/SurfaceComposerClient: ComposerService remote (surfaceflinger) died [0xf618d5c0]
02-23 05:02:11.844 1186-1186/? I/ServiceManager: service 'simphonebook' died
02-23 05:02:11.844 1186-1186/? I/ServiceManager: service 'iphonesubinfo' died
02-23 05:02:11.844 1186-1186/? I/ServiceManager: service 'isms' died
02-23 05:02:11.844 1186-1186/? I/ServiceManager: service 'phone' died
02-23 05:02:11.844 1186-1186/? I/ServiceManager: service 'carrier_config' died
02-23 05:02:11.844 1186-1186/? I/ServiceManager: service 'isub' died
02-23 05:02:12.527 1185-1185/? I/lowmemorykiller: ActivityManager disconnected
02-23 05:02:12.527 1185-1185/? I/lowmemorykiller: Closing Activity Manager data connection
02-23 05:02:12.527 1224-1224/? E/installd: eof
02-23 05:02:12.527 1224-1224/? E/installd: failed to read size
02-23 05:02:12.527 1224-1224/? I/installd: closing connection
02-23 05:02:12.532 1186-1186/? I/ServiceManager: service 'telecom' died
02-23 05:02:12.532 1250-1250/? D/fingerprintd: binder died
02-23 05:02:12.532 1250-1250/? V/fingerprintd: nativeCloseHal()
02-23 05:02:12.532 1250-1250/? D/FingerprintHal: ----------------> fingerprint_close ----------------->
02-23 05:02:12.532 1223-1814/? W/AudioFlinger: power manager service died !!!
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'input_method' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'netstats' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'netpolicy' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'wifip2p' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'wifi' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'wifiscanner' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'accessibility' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'mount' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'uimode' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'lock_settings' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'deviceidle' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'device_policy' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'statusbar' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'clipboard' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'package' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'user' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'activity' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'procstats' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'meminfo' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'rttmanager' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'gfxinfo' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'dbinfo' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'cpuinfo' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'permission' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'processinfo' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'sensorservice' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'battery' died
02-23 05:02:12.533 1186-1186/? I/ServiceManager: service 'usagestats' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'scheduling_policy' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'webviewupdate' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'telephony.registry' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'media.camera.proxy' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'account' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'content' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'launcherapps' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'network_management' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'vibrator' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'consumer_ir' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'alarm' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'window' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'input' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'batterystats' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'appops' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'power' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'display' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'connectivity' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'servicediscovery' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'updatelock' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'notification' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'devicestoragemonitor' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'location' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'country_detector' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'search' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'dropbox' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'wallpaper' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'media_projection' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'audio' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'DockObserver' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'midi' died
02-23 05:02:12.534 1186-1186/? I/ServiceManager: service 'usb' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'serial' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'jobscheduler' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'backup' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'textservices' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'network_score' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'appwidget' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'voiceinteraction' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'diskstats' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'samplingprofiler' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'commontime_management' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'dreams' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'assetatlas' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'graphicsstats' died
02-23 05:02:12.535 1186-1186/? I/ServiceManager: service 'print' died
02-23 05:02:12.536 1186-1186/? I/ServiceManager: service 'restrictions' died
02-23 05:02:12.536 1186-1186/? I/ServiceManager: service 'media_session' died
02-23 05:02:12.536 1186-1186/? I/ServiceManager: service 'media_router' died
02-23 05:02:12.536 1186-1186/? I/ServiceManager: service 'trust' died
02-23 05:02:12.536 1186-1186/? I/ServiceManager: service 'fingerprint' died
02-23 05:02:12.536 1186-1186/? I/ServiceManager: service 'imms' died

Image did not show up like in the 64 bit version, and there was this yellow box in the emulator:
![image](https://cloud.githubusercontent.com/assets/20513400/23245692/7ae6c62c-f9c9-11e6-8640-1c5b8c89d828.png)


Also, after generating the above logs, no more logs on the console even though the app is still within the emulator

**Comment by ivpusic** [comment] 2017-02-23 08:55
hm, so as far as I can see you got the image to react side...is image would are selecting very big? has something specific?

**Comment by gavin-gmlab** [comment] 2017-02-24 02:41
No, its a very small dummy image for testing. I have tried with various images and all the same, so its not like some sequence in the image. I think its some kind of memory leak. 

My RN is 39.2, "react": "~15.4.0-rc.4" if that is any help

**Comment by tanmynguyen** [comment] 2017-02-27 09:14
Yeah!! Thanks support by @ivpusic  i resolved it :)
I use 
1. react-native: 0.40.0
2. react-native-image-crop-picker: 0.12.4
and important : 
1. classpath 'com.android.tools.build:gradle:2.2.3' at android/build.gradle
2. distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip at android/gradle/gradle-wrapper.properties :)
I hope working with everyone :)

**Closed** 2017-02-27 09:15 UTC

**Comment by AE0011** [comment] 2018-11-27 11:06
@ivpusic 
I have still this issue 
https://github.com/ivpusic/react-native-image-crop-picker/issues/675#issuecomment-442017008
