### ISSUE TITLE
Crash when select image

### ISSUE THREAD

**Issue by Shirleyyyyy** [ivpusic/react-native-image-crop-picker#116] opened 2016-10-18 11:33 UTC
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.9.7
- react-native v0.35.0

### Platform
- Android

### Expected behaviour
Using the picker to select a image

### Actual behaviour
When I select a image,  the app crashed.

### Steps to reproduce

1.Open a picker

2.Select a image

3. Crashed

### Attachments

![image](https://cloud.githubusercontent.com/assets/22910920/19476028/9762c004-9569-11e6-9060-8377bd61e2a0.png)

![image](https://cloud.githubusercontent.com/assets/22910920/19476036/b1a53622-9569-11e6-8506-fa1666015fa0.png)

**Comment by ivpusic** [comment] 2016-10-18 16:24
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/99

**Closed by ivpusic** 2016-10-18 16:24 UTC
