### ISSUE TITLE
Application stop after openning photo gallery on Android.

### ISSUE THREAD

**Issue by fbonesso** [ivpusic/react-native-image-crop-picker#99] opened 2016-10-07 11:54 UTC
### Version
- react-native-image-crop-picker v0.9.7
- react-native v0.34.1

### Platform
- Android

### Expected behaviour
Run without crash in Emulator and Device.

### Actual behaviour
Application stop after opening the gallery and backing to application.

### Steps to reproduce

1. npm i react-native-image-crop-picker --save

2. react-native link react-native-image-crop-picker

3. react-native run-android

### Attachments
```

I/art: Waiting for a blocking GC DisableMovingGc
I/art: WaitForGcToComplete blocked for 8.218ms for cause DisableMovingGc
I/art: Starting a blocking GC DisableMovingGc

       [ 10-07 08:53:13.047  1620: 1649 D/         ]
       HostConnection::get() New Host Connection established 0x9ced7410, tid 1649
D/AndroidRuntime: Shutting down VM


                  --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.app.mobile, PID: 3092
                  java.lang.AbstractMethodError: abstract method "void com.facebook.react.bridge.ActivityEventListener.onActivityResult(android.app.Activity, int, int, android.content.Intent)"
                      at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:226)
                      at com.facebook.react.XReactInstanceManagerImpl.onActivityResult(XReactInstanceManagerImpl.java:616)
                      at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:134)
                      at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
                      at android.app.Activity.dispatchActivityResult(Activity.java:6428)
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
                      at android.app.ActivityThread.-wrap16(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by fbonesso** [comment] 2016-10-07 14:23
I rebuild everything to make sure that I was using the last version of React Native as well.

**Comment by ivpusic** [comment] 2016-10-07 14:25
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/97

**Closed by ivpusic** 2016-10-07 14:25 UTC

**Comment by fbonesso** [comment] 2016-10-07 16:58
Yes, but everything if updated, double check, clean and rebuild multiple times. Could be anything else?

**Comment by ivpusic** [comment] 2016-10-07 17:27
hm, I am pretty sure you still have older RN version in your Android Studio. I also got similar issue with some previous RN version.

**Comment by UlfR** [comment] 2016-10-15 16:20
i have same issue with same packages

**Comment by fbonesso** [comment] 2016-10-15 18:50
@ivpusic was right, I solve this removing gradlew cache folder and rebuild the project.

**Comment by UlfR** [comment] 2016-10-15 19:19
Sorry, i`ve tried to reproduce it on clean project. ImagePicker builds and works fine, so seems react-native update/configuration issue not ImagePicker.

**Comment by rmamtaventures** [comment] 2019-09-27 12:18
This issue come only on some specific android device like redmi, moto. Please help.
