### ISSUE TITLE
When i update Xcode to 8.3.1 ->Redefinition of module 'RSKImageCropper'

### ISSUE THREAD

**Issue by lenglengiOS** [ivpusic/react-native-image-crop-picker#303] opened 2017-04-15 01:48 UTC
### Version
Tell us which versions you are using: 

"react-native-image-crop-picker": "^0.12.6"
"react-native": "0.40.0"

### Platform
Tell us to which platform this issue is related
- iOS

![qq20170415-092226](https://cloud.githubusercontent.com/assets/21171262/25059829/921d6c50-21c0-11e7-8da6-7e5561396b81.png)

**Comment by ivpusic** [comment] 2017-04-15 10:49
duplicate of https://github.com/ivpusic/react-native-image-crop-picker/issues/286

**Closed by ivpusic** 2017-04-15 10:49 UTC
