### ISSUE TITLE
Cannot find image data

### ISSUE THREAD

**Issue by zrii** [ivpusic/react-native-image-crop-picker#118] opened 2016-10-20 12:58 UTC
### Version

Tell us which versions you are using: 
- react-native-image-crop-picker v0.10.1?.?
- react-native v0.35.0
### Platform

Tell us to which platform this issue is related
- Android
### Expected behaviour

Expected to always get the image form the camera
### Actual behaviour

Gets the image from the camera at apperently random, doesnt work 5x in a row, then does 3x or so...
### Steps to reproduce
1. Open cameraPicker and take a picture with any camera
2. Get the error message 2/3 of the time that there is no image data

3.
### Attachments

This is console from android studio when it does work.

10-20 14:52:37.815 7044-22007/com.testapp I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
10-20 14:52:37.862 7044-22007/com.testapp I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
10-20 14:52:37.936 7044-22006/com.testapp I/ReactNativeJS: 'Response = ', { customButton: 'cc' }
10-20 14:52:37.947 7044-22006/com.testapp I/ReactNativeJS: 'User tapped custom button: ', 'cc'
10-20 14:52:37.956 7044-8020/com.testapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb33bb400
10-20 14:52:37.989 7044-7044/com.testapp I/SensorManager: removeAllSensors() [Sensor: LGE Accelerometer] by com.facebook.react.common.ShakeDetector.stop():70
10-20 14:52:38.424 7044-8020/com.testapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x8cf83b30
10-20 14:52:49.257 7044-7044/com.testapp I/System.out: /data/user/0/com.testapp/cache/react-native-image-crop-picker
10-20 14:52:49.258 7044-7044/com.testapp I/Timeline: Timeline: Activity_launch_request id:com.testapp time:81376209
10-20 14:52:49.298 7044-7044/com.testapp I/SensorManager: registerListenerImpl() [Sensor: LGE Accelerometer, Rate: 66667, SensorEventListener: com.facebook.react.common.ShakeDetector@f0a89ba] by com.facebook.react.common.ShakeDetector.start():61
10-20 14:52:49.384 7044-8080/com.testapp W/unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
10-20 14:52:49.391 7044-7044/com.testapp I/SensorManager: removeAllSensors() [Sensor: LGE Accelerometer] by com.facebook.react.common.ShakeDetector.stop():70
10-20 14:52:49.441 7044-7044/com.testapp D/PhoneWindowEx: [PWEx][generateLayout] setLGNavigationBarColor : colors=0xfff5f5f5
10-20 14:52:49.442 7044-7044/com.testapp I/PhoneWindow: [setLGNavigationBarColor] color=0x fff5f5f5
10-20 14:52:49.523 7044-7044/com.testapp D/BitmapLoadUtils: maxBitmapSize: 2792
10-20 14:52:49.524 7044-11890/com.testapp D/BitmapWorkerTask: Uri scheme: file
10-20 14:52:49.532 7044-7044/com.testapp D/PhoneWindow: notifyNavigationBarColor, color=0x: fff5f5f5, token: android.view.ViewRootImplAO$WEx@32463f7
10-20 14:52:49.745 7044-7044/com.testapp V/ViewRootImpl: Contents drawing finished : com.testapp/com.yalantis.ucrop.UCropActivity
10-20 14:52:49.787 7044-8020/com.testapp E/Surface: getSlotFromBufferLocked: unknown buffer: 0x8cf833b0
10-20 14:52:49.945 7044-7044/com.testapp D/TransformImageView: Image size: [1080:1920]
10-20 14:52:49.984 7044-7044/com.testapp I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@115d3f6 time:81376935
10-20 14:52:49.985 7044-7044/com.testapp I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2417a99 time:81376936
10-20 14:52:52.882 7044-7044/com.testapp I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
10-20 14:52:52.961 7044-7044/com.testapp I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
10-20 14:52:52.964 7044-7044/com.testapp I/AudioManagerEx: AudioManagerEx created
10-20 14:52:53.044 7044-8058/com.testapp I/BitmapCropTask: Should crop: true
10-20 14:52:53.048 7044-8058/com.testapp D/uCrop JNI: Crop image with CImg
10-20 14:52:54.002 7044-7044/com.testapp I/SensorManager: registerListenerImpl() [Sensor: LGE Accelerometer, Rate: 66667, SensorEventListener: com.facebook.react.common.ShakeDetector@f0a89ba] by com.facebook.react.common.ShakeDetector.start():61
10-20 14:52:54.004 7044-22006/com.testapp I/ReactNativeJS: 'received image', { size: 18472,
                                                          mime: 'image/jpeg',
                                                          height: 300,
                                                          width: 300,
                                                          path: 'file:///data/user/0/com.testapp/cache/react-native-image-crop-picker/39d92881-21c1-4627-b51a-f5601cf71deb.jpg' }
10-20 14:52:54.009 7044-8010/com.testapp W/unknown:React: You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
10-20 14:52:54.138 7044-7044/com.testapp I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2417a99 time:81381089

And this is when it does not work.

10-20 14:55:18.105 7044-8058/com.testapp D/BitmapWorkerTask: Uri scheme: file
10-20 14:55:18.107 7044-8058/com.testapp D/skia: --- SkImageDecoder::Factory returned null
10-20 14:55:18.111 7044-7044/com.testapp D/PhoneWindow: notifyNavigationBarColor, color=0x: fff5f5f5, token: android.view.ViewRootImplAO$WEx@d5d75c2
10-20 14:55:18.147 7044-7044/com.testapp E/TransformImageView: onFailure: setImageUri
                                                            java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from the Uri: [file:///storage/emulated/0/Pictures/image-597c14d8-a158-491b-9645-c71356ff9005.jpg]
                                                                at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:113)
                                                                at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
                                                                at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
10-20 14:55:18.250 7044-7044/com.testapp V/ViewRootImpl: Contents drawing finished : com.testapp/com.yalantis.ucrop.UCropActivity

Thanks for all of the work you are doing!

P.S.
I guess I need to mention the device which is LG G3, or more precise 'LG-D855 - 6.0'

**Comment by ivpusic** [comment] 2016-10-20 13:18
Do you have a time to debug it? It is hard to help you because I cannot reproduce this issue on my devices at all.

**Comment by ivpusic** [comment] 2016-11-16 08:31
some recent updates may be helpful in resolving this. Please update to latest version and reopen if problem still exists for you

**Closed by ivpusic** 2016-11-16 08:31 UTC

**Comment by braco** [comment] 2017-06-12 23:55
Just starting getting this on iOS, will try and debug

**Comment by manojshrimalla** [comment] 2020-06-04 08:19
i have the same issue

**Comment by ilya-raevskiy** [comment] 2020-10-27 16:36
i have the same issue

**Comment by jd20** [comment] 2020-11-09 08:41
Same here, seeing this error occasionally with 0.32.2. Should we still expect the issue to be fixed on a later version?

**Comment by VBSwebs** [comment] 2020-12-05 10:06
same issue occure on selecting the image from gallery .My device is Hot 9 Play Infinix.

**Comment by lukebrandonfarrell** [comment] 2021-01-08 10:26
Still an issue, anyone got any information in this?

**Comment by Polinak87** [comment] 2021-01-27 11:18
i have the same issue

**Comment by FeMaffezzolli** [comment] 2021-02-19 16:50
Same problema here.

> Error: Cannot find image data
> at createErrorFromErrorData (NativeModules.js:155)

**Comment by wustzhy** [comment] 2023-01-16 03:56
A simple solution to fix 'cannot find image data', Go [here](https://github.com/ivpusic/react-native-image-crop-picker/issues/1367#issuecomment-1383440180)  for more information
