### ISSUE TITLE
pod install failed

### ISSUE THREAD

**Issue by satyagupta** [ivpusic/react-native-image-crop-picker#6] opened 2016-05-31 08:59 UTC
Same issue as https://github.com/ivpusic/react-native-image-crop-picker/issues/2

Here is the Podfile content
`pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'`

Which sits in the ios folder of the project. 

And here is the response that i get when i run pod install 
`[!] The dependency react-native-image-crop-picker (from ../node_modules/react-native-image-crop-picker/ios) is not used in any concrete target.`

**Comment by satyagupta** [comment] 2016-05-31 09:09
And if i change the content of podfile as you [suggested](https://github.com/ivpusic/react-native-image-crop-picker/issues/2#issuecomment-222502885) and do pod install i get following

> Analyzing dependencies
Fetching podspec for `React` from `../node_modules/react-native`
Fetching podspec for `react-native-image-crop-picker` from `../node_modules/react-native-image-crop-picker/ios`
[!] Unable to satisfy the following requirements:

> `react-native-image-crop-picker (from `../node_modules/react-native-image-crop-picker/ios`)` required by `Podfile`

>It seems like you've changed the constraints of dependency `react-native-image-crop-picker` inside your development pod `react-native-image-crop-picker`.
You should run `pod update react-native-image-crop-picker` to apply changes you've made.

And if i do pod update react-native-image-crop-picker then i get: 

>$ pod update react-native-image-crop-picker
[!] No `Podfile.lock' found in the project directory, run `pod install'.

**Comment by ivpusic** [comment] 2016-05-31 10:04
is there any chance to see example project where this can be reproduced? I tried it few times on fresh project, it works for me

**Comment by satyagupta** [comment] 2016-05-31 10:06
I will have to create a new RN, and test and get back to you. 

BTW what should be in the podfile and where should it sit?

**Comment by ivpusic** [comment] 2016-05-31 10:11
```
react-native init picker
cd picker
npm i react-native-image-crop-picker --save
cd ios
pod init
```

then in ios folder change Podfile to following

```
platform :ios, '8.0'

target 'picker' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
    pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'
end
```

then run pod install

and you should be done

**Comment by satyagupta** [comment] 2016-05-31 10:16
Here you go: https://github.com/satyagupta/Quadkopters

Podfile in the ios folder. 

doing pod install gives me this:

>$ pod install
Analyzing dependencies
[!] The dependency `react-native-image-crop-picker (from `../node_modules/react-native-image-crop-picker/ios`)` is not used in any concrete target.

BTW i will try you last suggestions and come back.

**Comment by satyagupta** [comment] 2016-05-31 10:18
Strange, now with your steps i get this 

>[!] Unable to find a specification for `QBImagePickerController (= 3.4.0)` depended upon by `react-native-image-crop-picker`

Podfile content:

platform :ios, '8.0'

target 'PROJECTNAME' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
    pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'
end

**Comment by ivpusic** [comment] 2016-05-31 10:25
```
platform :ios, '8.0'

target 'QuadKopters' do
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
    pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker/ios'
end
```

in you example project, change Podfile with this, and inside ios dir run `pod install`, and it should work.

**Comment by satyagupta** [comment] 2016-05-31 10:28
Same as last time:

`
[!] Unable to find a specification for 'QBImagePickerController (= 3.4.0)' depended upon by 'react-native-image-crop-picker'
`

**Comment by ivpusic** [comment] 2016-05-31 10:32
firewall issues or something similar? 

```pod search QBImagePickerController``` should give you `QBImagePickerController (3.4.0)` as available version.

**Comment by satyagupta** [comment] 2016-05-31 10:37
I am getting this: 
`$ pod search QBImagePickerController
Creating search index for spec repo 'master'.. Done!
[!] Unable to find a pod with name, author, summary, or descriptionmatching 'QBImagePickerController'`

**Comment by ivpusic** [comment] 2016-05-31 10:57
https://github.com/questbeat/QBImagePicker/blob/master/QBImagePickerController.podspec I think you have some other issue. check your firewall, network configuration and similar

**Comment by satyagupta** [comment] 2016-05-31 10:58
How do i confirm that? is there something else other POD which i can test/check it with?

**Comment by ivpusic** [comment] 2016-05-31 11:00
yes...you can follow something like this https://www.binpress.com/tutorial/cocoapods-dependancy-management-for-xcode/139

**Comment by satyagupta** [comment] 2016-05-31 11:13
`$ pod install
Setting up CocoaPods master repo`

Finally something is working, but its stucked on this screen. Anything you can help here?

**Comment by satyagupta** [comment] 2016-05-31 11:23
I got it, http://stackoverflow.com/questions/21022638/pod-install-is-staying-on-setting-up-cocoapods-master-repo

The repo is 350MB so its taking time to download the repo.. I guess i will have to wait for it. There is no other method to do this?

**Comment by ivpusic** [comment] 2016-05-31 11:29
just wait :)...will close this issue...if you still have troubles, please reopen

**Comment by satyagupta** [comment] 2016-05-31 11:30
Thanks @ivpusic 👍  appreciate you helping

**Closed by ivpusic** 2016-05-31 11:29 UTC

**Comment by satyagupta** [comment] 2016-06-01 04:10
Hello @ivpusic so finally the clone finished and pod install also worked fine. Now i am getting these errors 

http://grab.by/QvXY

**Comment by satyagupta** [comment] 2016-06-01 05:12
So there is no header folder inside node_modules/react-native-image-crop-picker/ios/Pods/ 

the header search path is as following:
>${PODS_ROOT}/Headers/Public
${PODS_ROOT}/Headers/Public/QBImagePickerController
${PODS_ROOT}/Headers/Public/RSKImageCropper
${PODS_ROOT}/Headers/Public/React
${PODS_ROOT}/Headers/Public/UIImage-Resize`

**Comment by satyagupta** [comment] 2016-06-01 05:57
And if i do pod install/update then following happen

>$ pod install
Re-creating CocoaPods due to major version update.
Analyzing dependencies
Fetching podspec for 'React' from '../node_modules/react-native'
[!] No podspec found for 'React' in '../node_modules/react-native'

>$ pod update
Update all pods
Re-creating CocoaPods due to major version update.
Updating local specs repositories
Analyzing dependencies
Fetching podspec for 'React' from '../node_modules/react-native'
[!] No podspec found for 'React' in '../node_modules/react-native'

**Comment by ivpusic** [comment] 2016-06-01 08:36
you should:

- make sure you have react-native installed (check node_modules)
- make sure `pod install` is not giving you any warnings (if yes, you should fix them => especially inherited flag warning)

**Comment by satyagupta** [comment] 2016-06-08 08:55
So finally i was able to get it installed and run the app without  any problem.

I have imported in the js file as you had mentioned but it was giving ImagePicker was undefined. 

When i did pod install i am getting this

>The dependency `react-native-image-crop-picker (from `../node_modules/react-native-image-crop-picker/ios`)` is not used in any concrete target.
