### ISSUE TITLE
after choice an image, auto close

### ISSUE THREAD

**Issue by ds-aco** [ivpusic/react-native-image-crop-picker#110] opened 2016-10-14 08:46 UTC
### Version
- react-native-image-crop-picker v0.10.0
- react-native v0.35.0
### Platform
- Android(MI NOTE PRO)
### Expected behaviour

 select multiple images
### Actual behaviour

when select one image ,the app is close
### Attachments

don't have any error report ,
(
    看得懂中文的应该更好理解我的问题,无论是单个图片还是多选图片,
    单个图片裁剪之后点确定的时候,多选选中一个图片的时候
    app就会闪退

)

**Comment by ds-aco** [comment] 2016-10-14 08:59
![z4 bww d7 ay l j_jup y](https://cloud.githubusercontent.com/assets/12523637/19381693/6c2ed8ba-922f-11e6-846f-6288a84eb860.png)
the code is very simple,

**Comment by ivpusic** [comment] 2016-10-14 11:53
can you please provide stacktrace when this error happens?

**Comment by ds-aco** [comment] 2016-10-17 08:14
it's don't have any error,  just when i confirm one picture  it's flash back(闪退).

npm i react-native-image-crop-picker --save
react-native link react-native-image-crop-picker
code and my environment is on the top 
am i  miss something?

**Comment by ivpusic** [comment] 2016-10-17 08:35
you should open your android studio, and there should be something in the console

**Comment by ds-aco** [comment] 2016-10-17 10:31
i can't provide it,   because i haven't use android studio ,this is a sad story

**Comment by ivpusic** [comment] 2016-10-17 10:46
then it is very hard to help you. Should be very easy to load project there and take stacktrace

**Comment by KsssAlleria** [comment] 2016-10-19 08:07
Same error!  The following is stacktrace.

`10-19 15:59:51.106 4006-4006/com.imagecrop W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x27cc0d88)
10-19 15:59:51.106 4006-4006/com.imagecrop E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.imagecrop, PID: 4006
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.imagecrop/com.yalantis.ucrop.UCropActivity}: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f02004f
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2207)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:140)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5113)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: android.content.res.Resources$NotFoundException: File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f02004f
                                                                 at android.content.res.Resources.loadDrawable(Resources.java:2160)
                                                                 at android.content.res.Resources.getDrawable(Resources.java:716)
                                                                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:194)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187)
                                                                 at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77)
                                                                 at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127)
                                                                 at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147)
                                                                 at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27)
                                                                 at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50)
                                                                 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201)
                                                                 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181)
                                                                 at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521)
                                                                 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
                                                                 at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106)
                                                                 at android.app.Activity.performCreate(Activity.java:5355)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1089)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:140) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596) 
                                                                 at dalvik.system.NativeStart.main(Native Method) 
                                                              Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: invalid drawable tag vector
                                                                 at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                                 at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                                                                 at android.content.res.Resources.loadDrawable(Resources.java:2156)
                                                                 at android.content.res.Resources.getDrawable(Resources.java:716) 
                                                                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:346) 
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:194) 
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:182) 
                                                                 at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:717) 
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:187) 
                                                                 at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:77) 
                                                                 at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:127) 
                                                                 at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:147) 
                                                                 at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:27) 
                                                                 at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:50) 
                                                                 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:201) 
                                                                 at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:181) 
                                                                 at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:521) 
                                                                 at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71) 
                                                                 at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:106) 
                                                                 at android.app.Activity.performCreate(Activity.java:5355) 
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1089) 
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171) 
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:140) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5113) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:780) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:596) 
                                                                 at dalvik.system.NativeStart.main(Native Method) 
10-19 16:00:14.686 4006-4006/com.imagecrop I/Process: Sending signal. PID: 4006 SIG: 9
`

**Comment by ivpusic** [comment] 2016-10-19 08:19
can you try this https://github.com/ivpusic/react-native-image-crop-picker/issues/106?

**Comment by ds-aco** [comment] 2016-10-19 10:01
i try this, it's not work too...
@KsssAlleria  how about you

**Comment by ds-aco** [comment] 2016-10-20 06:52
i try   com.android.tools.build:gradle:2.1.2 , but it's not ok 
so i try  com.android.tools.build:gradle:2.1.3 
when i react-native run-android,  it's had this error
![image](https://cloud.githubusercontent.com/assets/12523637/19548850/7a5f7df6-96d3-11e6-96fe-8ed4f1b520ec.png)

chinese => english 
错误:找不到符号 => error: can't find symbol
错误: PickerModule不是抽象的, 并且未覆盖ActivityEventListener中的抽象方法onActivityResult
=> error: PickerModule is not abstract, and not override ActivityEventListener's abstract function onActivityResult
 错误:方法不会覆盖或实现超类型的方法=> function can't override or implement super class's function

if you have time , @ivpusic

**Comment by ivpusic** [comment] 2016-10-20 07:16
@ds-aco I think you problem now is following https://github.com/ivpusic/react-native-image-crop-picker/issues/99

**Comment by ivpusic** [comment] 2016-10-22 00:39
@ds-aco any update?

**Comment by ds-aco** [comment] 2016-10-24 03:22
@ivpusic  i install a new react-native project and it's work good,..
but i think it's not a solve method,

**Comment by Jaafar-abusair** [comment] 2016-11-10 14:40
It's too simple, hold on the image when the picker open to select multiple images. enjoy ^^

**Comment by ivpusic** [comment] 2016-11-16 08:30
closing this. @ds-aco please reopen is problem still exists for you

**Closed by ivpusic** 2016-11-16 08:30 UTC
