### ISSUE TITLE
Images display problem

### ISSUE THREAD

**Issue by rishiankush** [ivpusic/react-native-image-crop-picker#609] opened 2018-02-07 12:01 UTC
I am facing an issue on real device(IOS).
When I upload an image it is successfully uploaded and visible on the screen for simulator. But, when I create a build and check in IOS device uploaded images does not display.

**Comment by ivpusic** [comment] 2018-02-09 23:11
hm, can you give me more details, because I cannot reproduce this issue?

**Comment by ivpusic** [comment] 2018-02-22 23:58
closing as there is not response from author

**Closed by ivpusic** 2018-02-22 23:58 UTC

**Comment by harikrishna1213** [comment] 2018-09-19 13:15
When i use this library in android it works perfectly. But when i upload image or take picture in ios device it loads image successfully for the first time. But its does't load image from the second time. It got stuck the process. 

Please give me solution on this for IOS device
