### ISSUE TITLE
issue displaying image from path on ios

### ISSUE THREAD

**Issue by mattBlackDesign** [ivpusic/react-native-image-crop-picker#24] opened 2016-07-17 16:25 UTC
I have successfully gotten the correct path returned, but when I try to display it, it appears blank. 

I have tried on both the simulator and on an actual device, and in both instances it returns blank. 

`<Image source={{uri: path, isStatic: true}} style={{height: 50, width: 50}} />`

**Comment by ivpusic** [comment] 2016-07-17 16:54
hmm, can you give me more details about image you are trying to display?

**Comment by mattBlackDesign** [comment] 2016-07-17 18:50
Is it a jpg image saved to camera roll. It is returning blank on ios.

**Comment by mattBlackDesign** [comment] 2016-07-17 19:01
Example image path would be "/private/var/mobile/Containers/Data/Application/953C0AD7-843C-4696-86F6-8B383128BA94/tmp/3D95FF6E-E8C6-481E-81B0-0D29295C61F0.jpg"

**Comment by ivpusic** [comment] 2016-07-17 19:08
and you run into this issue only when you select this particular image? if yes, can you please send me image which is causing issue?

**Comment by mattBlackDesign** [comment] 2016-07-17 19:49
The issue is occurring with all images. It doesn't matter which image I choose on the device.

**Comment by ivpusic** [comment] 2016-07-17 21:47
then it's really hard to say what is happening without taking closer look at your setup. To be sure that everything is ok with your project setup + image picker, can you please try running example project, and select image there? Or even better...can you try to debug issue? I can help you if you need any help during debugging.

**Comment by ivpusic** [comment] 2016-07-25 09:09
will close this one as obsolete. I am using module on real device / simulator on android/ios and I couldn't reproduce this issue. Please reopen if you have more info

**Closed by ivpusic** 2016-07-25 09:09 UTC

**Comment by gerard0315** [comment] 2016-11-03 19:31
@mattBlackDesign encountering the same problem, react native display warning 'Invalid prop source supplied to Image'

**Comment by Yuniac** [comment] 2023-04-17 20:35
Same here
